CREATE TABLE secu_todo(
	idPersona INT(10) PRIMARY KEY,

	apellido_paterno TEXT,
	apellido_materno TEXT,
	nombre TEXT,
	escuela TEXT,
	turno TEXT,
	grado_escolar TEXT,
	grupo  TEXT,
	edad INT(3),
	sexo TEXT,
	version_ex TEXT,
	
	el_es_una_pelota_de_fuego TEXT,
	a1 INT(3),
	es_una_pelota_de_plata TEXT,
	a2 INT(3),
	mi_es_una_pelota_de_pelos TEXT,
	a3 INT(3),
	la_frase_pelota_que_canta_tiene_sentido TEXT,
	por_que_pelota_que_canta TEXT,
	a4s INT(3),
	a4n INT(3),
	explica_lo_que_quiere_decir_mi_hermanito_es_una_pelota_de_gritos TEXT,
	a5 INT(3),
	que_otra_cosa_podria_ser_una_pelota_de_pelos TEXT,
	por_que_pelota_de_pelos TEXT,
	a6 INT(3),
	explica_tu_respuesta_en_la_frase_pelota_de_plata TEXT,
	a7 INT(3),
	total_a INT(3),
	
	PRUEBA_2 TEXT,--==========================================================
	
	c1_num_fr INT(3),
	c1_tipo TEXT,
	c1_frase TEXT,
	pregunta1 TEXT,
	c1t TEXT,
	concepto_r_1 TEXT,
	df_1 TEXT,
	c1_1 TEXT,
	c2_1 TEXT,
	c3_1 TEXT,
	criterio_1 TEXT,
	c1 INT(3),
	
	c2_num_fr INT(3),
	c2_tipo TEXT,
	c2_frase TEXT,
	pregunta2 TEXT,
	c2t TEXT,
	concepto_r_2 TEXT,
	df_2 TEXT,
	c1_2 TEXT,
	c2_2 TEXT,
	c3_2 TEXT,
	criterio_2 TEXT,
	c2 INT(3),
	
	c3_num_fr INT(3),
	c3_tipo TEXT,
	c3_frase TEXT,
	pregunta3 TEXT,
	c3t TEXT,
	concepto_r_3 TEXT,
	df_3 TEXT,
	c1_3 TEXT,
	c2_3 TEXT,
	c3_3 TEXT,
	criterio_3 TEXT,
	c3 INT(3),
	
	c4_num_fr INT(3),
	c4_tipo TEXT,
	c4_frase TEXT,
	pregunta4 TEXT,
	c4t TEXT,
	concepto_r_4 TEXT,
	df_4 TEXT,
	c1_4 TEXT,
	c2_4 TEXT,
	c3_4 TEXT,
	criterio_4 TEXT,
	c4 INT(3),
	
	c5_num_fr INT(3),
	c5_tipo TEXT,
	c5_frase TEXT,
	pregunta5 TEXT,
	c5t TEXT,
	concepto_r_5 TEXT,
	df_5 TEXT,
	c1_5 TEXT,
	c2_5 TEXT,
	c3_5 TEXT,
	criterio_5 TEXT,
	c5 INT(6),
	
	c6_num_fr INT(3),
	c6_tipo TEXT,
	c6_frase TEXT,
	pregunta6 TEXT,
	c6t TEXT,
	concepto_r_6 TEXT,
	df_6 TEXT,
	c1_6 TEXT,
	c2_6 TEXT,
	c3_6 TEXT,
	criterio_6 TEXT,
	c6 TEXT,
	
	PRUEBA_3 TEXT,--==========================================================
	
	b1__num_fr INT(3),
	b1_tipo TEXT,
	b1_frase TEXT,
	b1 INT(3),
	b1_comp INT(3),
	es_posible_1 TEXT,
	b1a INT(3),
	que_significa_1 TEXT,
	b1b INT(3),
	por_que_crees_que_si_o_no_es_posible_1 TEXT,
	b1c INT(3),
	b1_ruta TEXT,
	c1_b1 TEXT,
	c2_b1 TEXT,
	c3_b1 TEXT,
	c4_b1 TEXT,
	
	b2_num_fr INT(3),
	b2_tipo TEXT,
	b2_frase TEXT,
	b2 INT(3),
	b2_comp INT(3),
	es_posible_2 TEXT,
	b2a INT(3),
	que_significa_2 TEXT,
	b2b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_2 TEXT,
	b2c INT(3),
	b2_ruta TEXT,
	c1_b2 TEXT,
	c2_b2 TEXT,
	c3_b2 TEXT,
	c4_b2 TEXT,
	
	b3__num_fr INT(3),
	b3_tipo TEXT,
	b3_frase TEXT,
	b3 INT(3),
	b3_comp INT(3),
	es_posible_3 TEXT,
	b3a INT(3),
	que_significa_3 TEXT,
	b3b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_3 TEXT,
	b3c INT(3),
	b3_ruta TEXT,
	c1_b3 TEXT,
	c2_b3 TEXT,
	c3_b3 TEXT,
	c4_b3 TEXT,
	
	b4_num_fr INT(3),
	b4_tipo TEXT,
	b4_frase TEXT,
	b4 INT(3),
	b4_comp INT(3),
	es_posible_4 TEXT,
	b4a INT(3),
	que_significa_4 TEXT,
	b4b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_4 TEXT,
	b4c INT(3),
	b4_ruta TEXT,
	c1_b4 TEXT,
	c2_b4 TEXT,
	c3_b4 TEXT,
	c4_b4 TEXT,
	
	b5_num_fr INT(3),
	b5_tipo TEXT,
	b5_frase TEXT,
	b5 INT(3),
	b5_comp INT(3),
	es_posible_5 TEXT,
	b5a INT(3),
	que_significa_5 TEXT,
	b5b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_5 TEXT,
	b5c INT(3),
	b5_ruta TEXT,
	c1_b5 TEXT,
	c2_b5 TEXT,
	c3_b5 TEXT,
	c4_b5 TEXT,

	b6_num_fr INT(3),
	b6_tipo TEXT,
	b6_frase TEXT,
	b6 INT(3),
	b6_comp INT(3),
	es_posible_6 TEXT,
	b6a INT(3),
	que_significa_6 TEXT,
	b6b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_6 TEXT,
	b6c INT(3),
	b6_ruta TEXT,
	c1_b6 TEXT,
	c2_b6 TEXT,
	c3_b6 TEXT,
	c4_b6 TEXT,

	b7_num_fr INT(3),
	b7_tipo TEXT,
	b7_frase TEXT,
	b7 INT(3),
	b7_comp INT(3),
	es_posible_7 TEXT,
	b7a INT(3),
	que_significa_7 TEXT,
	b7b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_7 TEXT,
	b7c INT(3),
	b7_ruta TEXT,
	c1_b7 TEXT,
	c2_b7 TEXT,
	c3_b7 TEXT,
	c4_b7 TEXT,

	b8_num_fr INT(3),
	b8_tipo TEXT,
	b8_frase TEXT,
	b8 INT(3),
	b8_comp INT(3),
	es_posible_8 TEXT,
	b8a INT(3),
	que_significa_8 TEXT,
	b8b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_8 TEXT,
	b8c INT(3),
	b8_ruta TEXT,
	c1_b8 TEXT,
	c2_b8 TEXT,
	c3_b8 TEXT,
	c4_b8 TEXT,

	b9_num_fr INT(3),
	b9_tipo TEXT,
	b9_frase TEXT,
	b9 INT(3),
	b9_comp INT(3),
	es_posible_9 TEXT,
	b9a INT(3),
	que_significa_9 TEXT,
	b9b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_9 TEXT,
	b9c INT(3),
	b9_ruta TEXT,
	c1_b9 TEXT,
	c2_b9 TEXT,
	c3_b9 TEXT,
	c4_b9 TEXT,
	
	PRUEBA_4 TEXT,--==========================================================
	
	d_tipo INT(3),

	clave_1 TEXT,
    d1_tipo TEXT,
    simon_ha_estado_caminando_en_la_nieve_por_horas_sus_pies TEXT,
    d1 TEXT, -- tiene abcd o numeros
    
    clave_2 TEXT,
    d2_tipo TEXT,
    el_arbol_de_mi_jardin_ha_crecido_mucho_este_ano TEXT,
    d2 TEXT, -- tiene abcd o numeros

    clave_3 TEXT,
    d3_tipo TEXT,
    mi_mama_dejo_el_pan_afuera_toda_la_noche_en_la_manana TEXT,
    d3 TEXT, -- tiene abcd o numeros

    clave_4 TEXT,
    d4_tipo TEXT,
    mi_amigo_de_la_escuela_siempre_me_protege_de_los_bravucones_el TEXT,
    d4 TEXT, -- tiene abcd o numeros
    
    clave_5 TEXT,
    d5_tipo TEXT,
    laura_habla_tan_suavemente_que_apenas_puedes_oirla_ella TEXT,
    d5 TEXT, -- tiene abcd o numeros
    
    clave_6 TEXT,
    d6_tipo TEXT,
    jeny_siempre_saca_buenas_calificaciones_en_sus_examenes_ella_es TEXT,
    d6 TEXT, -- tiene abcd o numeros
    
    clave_7 TEXT,
    d7_tipo TEXT,
    mi_papa_estaba_muy_enojado_cuando_llegue_tarde_a_la_casa_el TEXT,
    d7 TEXT, -- tiene abcd o numeros
    
    clave_8 TEXT,
    d8_tipo TEXT,
    peter_puede_levantar_cosas_muy_pesadas_sin_ningun_problema_el TEXT,
    d8 TEXT, -- tiene abcd o numeros
    
    clave_9 TEXT,
    d9_tipo TEXT,
    nuestra_nueva_escuela_es_muy_grande_y_yo_siempre_me_pierdo TEXT,
    d9 TEXT, -- tiene abcd o numeros
    
    clave_10 TEXT,
    d10_tipo TEXT,
    las_unas_largas_de_july_estan_pintadas_de_rojo_y_dorado TEXT,
    d10 TEXT, -- tiene abcd o numeros
    
    clave_11 TEXT,
    d11_tipo TEXT,
    luis_siempre_esta_contento_y_eso_hace_sentir_bien_a_los_demas_el TEXT,
    d11 TEXT, -- tiene abcd o numeros
    
    clave_12 TEXT,
    d12_tipo TEXT,
    paty_tiene_el_pelo_muy_largo_y_liso_su_cabello TEXT,
    d12 TEXT, -- tiene abcd o numeros
    
    clave_13 TEXT,
    d13_tipo TEXT,
    joe_paso_mucho_tiempo_en_la_alberca_el TEXT,
    d13 TEXT, -- tiene abcd o numeros
    
    clave_14 TEXT,
    d14_tipo TEXT,
    el_nuevo_perro_de_sam_es_muy_grande TEXT,
    d14 TEXT, -- tiene abcd o numeros
    
    clave_15 TEXT,
    d15_tipo TEXT,
    luisa_ha_estado_gritando_y_llorando_por_horas_ella TEXT,
    d15 TEXT, -- tiene abcd o numeros
    
    clave_16 TEXT,
    d16_tipo TEXT,
    la_calefaccion_ha_estado_prendida_por_horas_y_la_habitacion TEXT,
    d16 TEXT, -- tiene abcd o numeros
    
    clave_17 TEXT,
    d17_tipo TEXT,
    kate_tiene_una_linda_cara_y_bonitos_ojos_ella TEXT,
    d17 TEXT, -- tiene abcd o numeros
    
    clave_18 TEXT,
    d18_tipo TEXT,
    julian_esta_escondido_detras_del_arbol_sin_moverse_el_es TEXT,
    d18 TEXT, -- tiene abcd o numeros
    
    total_d INT(3)

);
