SET GLOBAL innodb_default_row_format='dynamic';
SET SESSION innodb_strict_mode=OFF;
SELECT * FROM prim_todo;
CREATE TABLE prim_todo(
	
	idPersona INT(10) PRIMARY KEY,
	participante TEXT,
	escuela TEXT,
	grado_escolar TEXT,
	edad INT(3),
	sexo TEXT,
	
	
	el_es_una_pelota_de_fuego TEXT,
	a1 INT(3),
	es_una_pelota_de_plata TEXT,
	a2 INT(3),
	mi_es_una_pelota_de_pelos TEXT,
	a3 INT(3),
	por_que_pelota_que_canta_si TEXT,
	a4s INT(3),
	por_que_pelota_que_canta_no TEXT,
	a4n INT(10),
	explica_lo_que_quiere_decir_mi_hermanito_es_una_pelota_de_gritos TEXT,
	a5 INT(3),
	que_otra_cosa_podria_ser_una_pelota_de_pelos TEXT,
	a6 INT(3),
	explica_tu_respuesta_en_la_frase_pelota_de_plata TEXT,
	a7 INT(3),
	total_a INT(3),
	
	
	PRUEBA_2 TEXT,
	
	
	c1_num_fr INT(3),
	c1_frase TEXT,
	pregunta1 TEXT,
	c1t TEXT,
	concepto_r_1 TEXT,
	df_1 TEXT,
	c1_1 TEXT,
	c2_1 TEXT,
	c3_1 TEXT,
	criterio_1 TEXT,
	c1 INT(3),
	
	
	c2_num_fr INT(3),
	c2_frase TEXT,
	pregunta2 TEXT,
	c2t TEXT,
	concepto_r_2 TEXT,
	df_2 TEXT,
	c1_2 TEXT,
	c2_2 TEXT,
	c3_2 TEXT,
	c4_2 TEXT,
	criterio_2 TEXT,
	c2 INT(3),
	
	c3_num_fr INT(3),
	c3_frase TEXT,
	pregunta3 TEXT,
	c3t TEXT,
	concepto_r_3 TEXT,
	df_3 TEXT,
	c1_3 TEXT,
	c2_3 TEXT,
	c3_3 TEXT,
	c4_3 TEXT,
	criterio_3 TEXT,
	c3 INT(3),
	
	c4_num_fr INT(3),
	c4_frase TEXT,
	pregunta4 TEXT,
	c4t TEXT,
	concepto_r_4 TEXT,
	df_4 TEXT,
	c1_4 TEXT,
	c2_4 TEXT,
	c3_4 TEXT,
    c4_4 TEXT,
	criterio_4 TEXT,
	c4 INT(3),
	
	c5_num_fr INT(3),
	c5_frase TEXT,
	pregunta5 TEXT,
	c5t TEXT,
	concepto_r_5 TEXT,
	df_5 TEXT,
	c1_5 TEXT,
	c2_5 TEXT,
	c3_5 TEXT,
	c4_5 TEXT,
	criterio_5 TEXT,
	c5 INT(6),
	
	c6_num_fr INT(3),
	c6_frase TEXT,
	pregunta6 TEXT,
	c6t TEXT,
	concepto_r_6 TEXT,
	df_6 TEXT,
	c1_6 TEXT,
	c2_6 TEXT,
	c3_6 TEXT,
	criterio_6 TEXT,
	c6 TEXT,
	
	PRUEBA_3 TEXT,
	
	b1__num_fr INT(3),
	b1_frase TEXT,
	b1 INT(3),
	es_posible_1 TEXT,
	b1a INT(3),
	que_significa_1 TEXT,
	b1b INT(3),
	por_que_crees_que_si_o_no_es_posible_1 TEXT,
	b1c INT(3),
	b1_ruta TEXT,
	c1_b1 TEXT,
	c2_b1 TEXT,
	c3_b1 TEXT,
	c4_b1 TEXT,
	
	b2_num_fr INT(3),
	b2_frase TEXT,
	b2 INT(3),
	es_posible_2 TEXT,
	b2a INT(3),
	que_significa_2 TEXT,
	b2b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_2 TEXT,
	b2c INT(3),
	b2_ruta TEXT,
	c1_b2 TEXT,
	c2_b2 TEXT,
	c3_b2 TEXT,
	
	b3__num_fr INT(3),
	b3_frase TEXT,
	b3 INT(3),
	es_posible_3 TEXT,
	b3a INT(3),
	que_significa_3 TEXT,
	b3b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_3 TEXT,
	b3c INT(3),
	b3_ruta TEXT,
	c1_b3 TEXT,
	c2_b3 TEXT,
	c3_b3 TEXT,
	
	b4__num_fr INT(3),
	b4_frase TEXT,
	b4 INT(3),
	es_posible_4 TEXT,
	b4a INT(3),
	que_significa_4 TEXT,
	b4b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_4 TEXT,
	b4c INT(3),
	b4_ruta TEXT,
	c1_b4 TEXT,
	c2_b4 TEXT,
	c3_b4 TEXT,
	
	b5__num_fr INT(3),
	b5_frase TEXT,
	b5 INT(3),
	es_posible_5 TEXT,
	b5a INT(3),
	que_significa_5 TEXT,
	b5b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_5 TEXT,
	b5c INT(3),
	b5_ruta TEXT,
	c1_b5 TEXT,
	c2_b5 TEXT,
	c3_b5 TEXT,
	c4_b5 TEXT,

	b6__num_fr INT(3),
	b6_frase TEXT,
	b6 INT(3),
	es_posible_6 TEXT,
	b6a INT(3),
	que_significa_6 TEXT,
	b6b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_6 TEXT,
	b6c INT(3),
	b6_ruta TEXT,
	c1_b6 TEXT,
	c2_b6 TEXT,
	c3_b6 TEXT,

	b7__num_fr INT(3),
	b7_frase TEXT,
	b7 INT(3),
	es_posible_7 TEXT,
	b7a INT(3),
	que_significa_7 TEXT,
	b7b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_7 TEXT,
	b7c INT(3),
	b7_ruta TEXT,
	c1_b7 TEXT,
	c2_b7 TEXT,
	c3_b7 TEXT,

	b8__num_fr INT(3),
	b8_frase TEXT,
	b8 INT(3),
	es_posible_8 TEXT,
	b8a INT(3),
	que_significa_8 TEXT,
	b8b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_8 TEXT,
	b8c INT(3),
	b8_ruta TEXT,
	c1_b8 TEXT,
	c2_b8 TEXT,
	
	b9__num_fr INT(3),
	b9_frase TEXT,
	b9 INT(3),
	es_posible_9 TEXT,
	b9a INT(3),
	que_significa_9 TEXT,
	b9b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_9 TEXT,
	b9c INT(3),
	b9_ruta TEXT,
	c1_b9 TEXT,
	c2_b9 TEXT,
	c3_b9 TEXT,
	
	b10__num_fr INT(3),
	b10_frase TEXT,
	b10 INT(3),
	es_posible_10 TEXT,
	b10a INT(3),
	que_significa_10 TEXT,
	b10b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_10 TEXT,
	b10c INT(3),
	b10_ruta TEXT,
	c1_b10 TEXT,
	c2_b10 TEXT,
	c3_b10 TEXT,
	
	b11__num_fr INT(3),
	b11_frase TEXT,
	b11 INT(3),
	es_posible_11 TEXT,
	b11a INT(3),
	que_significa_11 TEXT,
	b11b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_11 TEXT,
	b11c INT(3),
	b11_ruta TEXT,
	c1_b11 TEXT,
	c2_b11 TEXT,
	c3_b11 TEXT,
	
	b12__num_fr INT(3),
	b12_frase TEXT,
	b12 INT(3),
	es_posible_12 TEXT,
	b12a INT(3),
	que_significa_12 TEXT,
	b12b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_12 TEXT,
	b12c INT(3),
	b12_ruta TEXT,
	c1_b12 TEXT,
	c2_b12 TEXT,
	c3_b12 TEXT,

	b13__num_fr INT(3),
	b13_frase TEXT,
	b13 INT(3),
	es_posible_13 TEXT,
	b13a INT(3),
	que_significa_13 TEXT,
	b13b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_13 TEXT,
	b13c INT(3),
	b13_ruta TEXT,
	c1_b13 TEXT,
	c2_b13 TEXT,
	c3_b13 TEXT,

	b14__num_fr INT(3),
	b14_frase TEXT,
	b14 INT(3),
	es_posible_14 TEXT,
	b14a INT(3),
	que_significa_14 TEXT,
	b14b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_14 TEXT,
	b14c INT(3),
	b14_ruta TEXT,
	c1_b14 TEXT,
	c2_b14 TEXT,

	b15__num_fr INT(3),
	b15_frase TEXT,
	b15 INT(3),
	es_posible_15 TEXT,
	b15a INT(3),
	que_significa_15 TEXT,
	b15b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_15 TEXT,
	b15c INT(3),
	b15_ruta TEXT,
	c1_b15 TEXT,
	c2_b15 TEXT,
	

	b16__num_fr INT(3),
	b16_frase TEXT,
	b16 INT(3),
	es_posible_16 TEXT,
	b16a INT(3),
	que_significa_16 TEXT,
	b16b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_16 TEXT,
	b16c INT(3),
	b16_ruta TEXT,
	c1_b16 TEXT,
	c2_b16 TEXT,
	
	b17__num_fr INT(3),
	b17_frase TEXT,
	b17 INT(3),
	es_posible_17 TEXT,
	b17a INT(3),
	que_significa_17 TEXT,
	b17b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_17 TEXT,
	b17c INT(3),
	b17_ruta TEXT,
	c1_b17 TEXT,
	c2_b17 TEXT,

	b18__num_fr INT(3),
	b18_frase TEXT,
	b18 INT(3),
	es_posible_18 TEXT,
	b18a INT(3),
	que_significa_18 TEXT,
	b18b INT(3),
	por_que_crees_que_si_o_que_no_es_posible_18 TEXT,
	b18c INT(3),
	b18_ruta TEXT,
	c1_b18 TEXT,
	c2_b18 TEXT,
	c3_b18 TEXT,
	califico TEXT,
	
	PRUEBA_4 TEXT,
	d_tipo INT(3),
	clave_1 TEXT,
    d1_tipo TEXT,
    simon_ha_estado_caminando_en_la_nieve_por_horas_sus_pies TEXT,
    d1 TEXT, 
    clave_2 TEXT,
    d2_tipo TEXT,
    el_arbol_de_mi_jardin_ha_crecido_mucho_este_ano TEXT,
    d2 TEXT, 

    clave_3 TEXT,
    d3_tipo TEXT,
    mi_mama_dejo_el_pan_afuera_toda_la_noche_en_la_manana TEXT,
    d3 TEXT, 

    clave_4 TEXT,
    d4_tipo TEXT,
    mi_amigo_de_la_escuela_siempre_me_protege_de_los_bravucones_el TEXT,
    d4 TEXT, 
    
    clave_5 TEXT,
    d5_tipo TEXT,
    laura_habla_tan_suavemente_que_apenas_puedes_oirla_ella TEXT,
    d5 TEXT, 
    
    clave_6 TEXT,
    d6_tipo TEXT,
    jeny_siempre_saca_buenas_calificaciones_en_sus_examenes_ella_es TEXT,
    d6 TEXT, 
    
    clave_7 TEXT,
    d7_tipo TEXT,
    mi_papa_estaba_muy_enojado_cuando_llegue_tarde_a_la_casa_el TEXT,
    d7 TEXT, 
    
    clave_8 TEXT,
    d8_tipo TEXT,
    peter_puede_levantar_cosas_muy_pesadas_sin_ningun_problema_el TEXT,
    d8 TEXT, 
    
    clave_9 TEXT,
    d9_tipo TEXT,
    nuestra_nueva_escuela_es_muy_grande_y_yo_siempre_me_pierdo TEXT,
    d9 TEXT, 
    
    clave_10 TEXT,
    d10_tipo TEXT,
    las_unas_largas_de_july_estan_pintadas_de_rojo_y_dorado TEXT,
    d10 TEXT, 
    
    clave_11 TEXT,
    d11_tipo TEXT,
    luis_siempre_esta_contento_y_eso_hace_sentir_bien_a_los_demas_el TEXT,
    d11 TEXT, 
    
    clave_12 TEXT,
    d12_tipo TEXT,
    paty_tiene_el_pelo_muy_largo_y_liso_su_cabello TEXT,
    d12 TEXT, 
    
    clave_13 TEXT,
    d13_tipo TEXT,
    joe_paso_mucho_tiempo_en_la_alberca_el TEXT,
    d13 TEXT, 
    
    clave_14 TEXT,
    d14_tipo TEXT,
    el_nuevo_perro_de_sam_es_muy_grande TEXT,
    d14 TEXT, 
    
    clave_15 TEXT,
    d15_tipo TEXT,
    luisa_ha_estado_gritando_y_llorando_por_horas_ella TEXT,
    d15 TEXT, 
    
    clave_16 TEXT,
    d16_tipo TEXT,
    la_calefaccion_ha_estado_prendida_por_horas_y_la_habitacion TEXT,
    d16 TEXT, 
    
    clave_17 TEXT,
    d17_tipo TEXT,
    kate_tiene_una_linda_cara_y_bonitos_ojos_ella TEXT,
    d17 TEXT, 
    
    clave_18 TEXT,
    d18_tipo TEXT,
    julian_esta_escondido_detras_del_arbol_sin_moverse_el_es TEXT,
    d18 TEXT,
    
    total_d INT(3)

);