CREATE TABLE secu_todo(
	idPersona INT(10) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(idPersona)

	apellido_paterno VARCHAR,
	apellido_materno VARCHAR,
	nombre VARCHAR,
	escuela VARCHAR,
	turno VARCHAR,
	grado_escolar VARCHAR,
	grupo  VARCHAR,
	edad INT(3),
	sexo VARCHAR,
	version_ex VARCHAR,
	
	el_es_una_pelota_de_fuego VARCHAR,
	a1 INT(3),
	es_una_pelota_de_plata VARCHAR,
	a2 INT(3),
	mi_es_una_pelota_de_pelos VARCHAR,
	a3 INT(3),
	la_frase_pelota_que_canta_tiene_sentido? VARCHAR,
	por_que_pelota_que_canta? VARCHAR,
	a4s INT(3),
	a4n INT(3),
	explica_lo_que_quiere_decir_mi_hermanito_es_una_pelota_de_gritos VARCHAR,
	a5 INT(3),
	que_otra_cosa_podria_ser_una_pelota_de_pelos? VARCHAR,
	por_que_pelota_de_pelos? VARCHAR,
	a6 INT(3),
	explica_tu_respuesta_en_la_frase_pelota_de_plata VARCHAR,
	a7 INT(3),
	total_a INT(3),
	
	PRUEBA_2 VARCHAR,--==========================================================
	
	c1_num_fr INT(3),
	c1_tipo VARCHAR,
	c1_frase VARCHAR,
	pregunta1 VARCHAR,
	c1t VARCHAR,
	concepto_r_1 VARCHAR,
	df_1 VARCHAR,
	c1_1 VARCHAR,
	c2_1 VARCHAR,
	c3_1 VARCHAR,
	criterio_1 VARCHAR,
	c1 INT(3),
	
	c2_num_fr INT(3),
	c2_tipo VARCHAR,
	c2_frase VARCHAR,
	pregunta2 VARCHAR,
	c2t VARCHAR,
	concepto_r_2 VARCHAR,
	df_2 VARCHAR,
	c1_2 VARCHAR,
	c2_2 VARCHAR,
	c3_2 VARCHAR,
	criterio_2 VARCHAR,
	c2 INT(3),
	
	c3_num_fr INT(3),
	c3_tipo VARCHAR,
	c3_frase VARCHAR,
	pregunta3 VARCHAR,
	c3t VARCHAR,
	concepto_r_3 VARCHAR,
	df_3 VARCHAR,
	c1_3 VARCHAR,
	c2_3 VARCHAR,
	c3_3 VARCHAR,
	criterio_3 VARCHAR,
	c3 INT(3),
	
	c4_num_fr INT(3),
	c4_tipo VARCHAR,
	c4_frase VARCHAR,
	pregunta4 VARCHAR,
	c4t VARCHAR,
	concepto_r_4 VARCHAR,
	df_4 VARCHAR,
	c1_4 VARCHAR,
	c2_4 VARCHAR,
	c3_4 VARCHAR,
	criterio_4 VARCHAR,
	c4 INT(3),
	
	c5_num_fr INT(3),
	c5_tipo VARCHAR,
	c5_frase VARCHAR,
	pregunta5 VARCHAR,
	c5t VARCHAR,
	concepto_r_5 VARCHAR,
	df_5 VARCHAR,
	c1_5 VARCHAR,
	c2_5 VARCHAR,
	c3_5 VARCHAR,
	criterio_5 VARCHAR,
	c5 INT(6),
	
	c6_num_fr INT(3),
	c6_tipo VARCHAR,
	c6_frase VARCHAR,
	pregunta6 VARCHAR,
	c6t VARCHAR,
	concepto_r_6 VARCHAR,
	df_6 VARCHAR,
	c1_6 VARCHAR,
	c2_6 VARCHAR,
	c3_6 VARCHAR,
	criterio_6 VARCHAR,
	c6 VARCHAR,
	
	PRUEBA_3 VARCHAR,--==========================================================
	
	b1__num_fr INT(3),
	b1_tipo VARCHAR,
	b1_frase VARCHAR,
	b1 INT(3),
	b1_comp INT(3),
	es_posible?_1 VARCHAR,
	b1a INT(3),
	que_significa?_1 VARCHAR,
	b1b INT(3),
	por_que_crees_que_si_o_no_es_posible?_1 VARCHAR,
	b1c INT(3),
	b1_ruta VARCHAR,
	c1_b1 VARCHAR,
	c2_b1 VARCHAR,
	c3_b1 VARCHAR,
	c4_b1 VARCHAR,
	
	b2_num_fr INT(3),
	b2_tipo VARCHAR,
	b2_frase VARCHAR,
	b2 INT(3),
	b2_comp INT(3),
	es_posible?_2 VARCHAR,
	b2a INT(3),
	que_significa?_2 VARCHAR,
	b2b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_2 VARCHAR,
	b2c INT(3),
	b2_ruta VARCHAR,
	c1_b2 VARCHAR,
	c2_b2 VARCHAR,
	c3_b2 VARCHAR,
	c4_b2 VARCHAR,
	
	b3__num_fr INT(3),
	b3_tipo VARCHAR,
	b3_frase VARCHAR,
	b3 INT(3),
	b3_comp INT(3),
	es_posible?_3 VARCHAR,
	b3a INT(3),
	que_significa?_3 VARCHAR,
	b3b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_3 VARCHAR,
	b3c INT(3),
	b3_ruta VARCHAR,
	c1_b3 VARCHAR,
	c2_b3 VARCHAR,
	c3_b3 VARCHAR,
	c4_b3 VARCHAR,
	
	b4_num_fr INT(3),
	b4_tipo VARCHAR,
	b4_frase VARCHAR,
	b4 INT(3),
	b4_comp INT(3),
	es_posible?_4 VARCHAR,
	b4a INT(3),
	que_significa?_4 VARCHAR,
	b4b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_4 VARCHAR,
	b4c INT(3),
	b4_ruta VARCHAR,
	c1_b4 VARCHAR,
	c2_b4 VARCHAR,
	c3_b4 VARCHAR,
	c4_b4 VARCHAR,
	
	b5_num_fr INT(3),
	b5_tipo VARCHAR,
	b5_frase VARCHAR,
	b5 INT(3),
	b5_comp INT(3),
	es_posible?_5 VARCHAR,
	b5a INT(3),
	que_significa?_5 VARCHAR,
	b5b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_5 VARCHAR,
	b5c INT(3),
	b5_ruta VARCHAR,
	c1_b5 VARCHAR,
	c2_b5 VARCHAR,
	c3_b5 VARCHAR,
	c4_b5 VARCHAR,

	b6_num_fr INT(3),
	b6_tipo VARCHAR,
	b6_frase VARCHAR,
	b6 INT(3),
	b6_comp INT(3),
	es_posible?_6 VARCHAR,
	b6a INT(3),
	que_significa?_6 VARCHAR,
	b6b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_6 VARCHAR,
	b6c INT(3),
	b6_ruta VARCHAR,
	c1_b6 VARCHAR,
	c2_b6 VARCHAR,
	c3_b6 VARCHAR,
	c4_b6 VARCHAR,

	b7_num_fr INT(3),
	b7_tipo VARCHAR,
	b7_frase VARCHAR,
	b7 INT(3),
	b7_comp INT(3),
	es_posible?_7 VARCHAR,
	b7a INT(3),
	que_significa?_7 VARCHAR,
	b7b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_7 VARCHAR,
	b7c INT(3),
	b7_ruta VARCHAR,
	c1_b7 VARCHAR,
	c2_b7 VARCHAR,
	c3_b7 VARCHAR,
	c4_b7 VARCHAR,

	b8_num_fr INT(3),
	b8_tipo VARCHAR,
	b8_frase VARCHAR,
	b8 INT(3),
	b8_comp INT(3),
	es_posible?_8 VARCHAR,
	b8a INT(3),
	que_significa?_8 VARCHAR,
	b8b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_8 VARCHAR,
	b8c INT(3),
	b8_ruta VARCHAR,
	c1_b8 VARCHAR,
	c2_b8 VARCHAR,
	c3_b8 VARCHAR,
	c4_b8 VARCHAR,

	b9_num_fr INT(3),
	b9_tipo VARCHAR,
	b9_frase VARCHAR,
	b9 INT(3),
	b9_comp INT(3),
	es_posible?_9 VARCHAR,
	b9a INT(3),
	que_significa?_9 VARCHAR,
	b9b INT(3),
	por_que_crees_que_si_o_que_no_es_posible?_9 VARCHAR,
	b9c INT(3),
	b9_ruta VARCHAR,
	c1_b9 VARCHAR,
	c2_b9 VARCHAR,
	c3_b9 VARCHAR,
	c4_b9 VARCHAR,
	
	PRUEBA_4 VARCHAR,--==========================================================
	
	d1_tipo INT(3),

	clave_1 VARCHAR,
    d1_tipo VARCHAR,
    simon_ha_estado_caminando_en_la_nieve_por_horas_sus_pies VARCHAR,
    d1 VARCHAR, -- tiene abcd o numeros
    
    clave_2 VARCHAR,
    d2_tipo VARCHAR,
    el_arbol_de_mi_jardin_ha_crecido_mucho_este_ano VARCHAR,
    d2 VARCHAR, -- tiene abcd o numeros

    clave_3 VARCHAR,
    d3_tipo VARCHAR,
    mi_mama_dejo_el_pan_afuera_toda_la_noche_en_la_manana VARCHAR,
    d3 VARCHAR, -- tiene abcd o numeros

    clave_4 VARCHAR,
    d4_tipo VARCHAR,
    mi_amigo_de_la_escuela_siempre_me_protege_de_los_bravucones_el VARCHAR,
    d4 VARCHAR, -- tiene abcd o numeros
    
    clave_5 VARCHAR,
    d5_tipo VARCHAR,
    laura_habla_tan_suavemente_que_apenas_puedes_oirla_ella VARCHAR,
    d5 VARCHAR, -- tiene abcd o numeros
    
    clave_6 VARCHAR,
    d6_tipo VARCHAR,
    jeny_siempre_saca_buenas_calificaciones_en_sus_examenes_ella_es VARCHAR,
    d6 VARCHAR, -- tiene abcd o numeros
    
    clave_7 VARCHAR,
    d7_tipo VARCHAR,
    mi_papa_estaba_muy_enojado_cuando_llegue_tarde_a_la_casa_el VARCHAR,
    d7 VARCHAR, -- tiene abcd o numeros
    
    clave_8 VARCHAR,
    d8_tipo VARCHAR,
    peter_puede_levantar_cosas_muy_pesadas_sin_ningun_problema_el VARCHAR,
    d8 VARCHAR, -- tiene abcd o numeros
    
    clave_9 VARCHAR,
    d9_tipo VARCHAR,
    nuestra_nueva_escuela_es_muy_grande_y_yo_siempre_me_pierdo VARCHAR,
    d9 VARCHAR, -- tiene abcd o numeros
    
    clave_10 VARCHAR,
    d10_tipo VARCHAR,
    las_unas_largas_de_july_estan_pintadas_de_rojo_y_dorado VARCHAR,
    d10 VARCHAR, -- tiene abcd o numeros
    
    clave_11 VARCHAR,
    d11_tipo VARCHAR,
    luis_siempre_esta_contento_y_eso_hace_sentir_bien_a_los_demas_el VARCHAR,
    d11 VARCHAR, -- tiene abcd o numeros
    
    clave_12 VARCHAR,
    d12_tipo VARCHAR,
    paty_tiene_el_pelo_muy_largo_y_liso_su_cabello VARCHAR,
    d12 VARCHAR, -- tiene abcd o numeros
    
    clave_13 VARCHAR,
    d13_tipo VARCHAR,
    joe_paso_mucho_tiempo_en_la_alberca_el VARCHAR,
    d13 VARCHAR, -- tiene abcd o numeros
    
    clave_14 VARCHAR,
    d14_tipo VARCHAR,
    el_nuevo_perro_de_sam_es_muy_grande VARCHAR,
    d14 VARCHAR, -- tiene abcd o numeros
    
    clave_15 VARCHAR,
    d15_tipo VARCHAR,
    luisa_ha_estado_gritando_y_llorando_por_horas_ella VARCHAR,
    d15 VARCHAR, -- tiene abcd o numeros
    
    clave_16 VARCHAR,
    d16_tipo VARCHAR,
    la_calefaccion_ha_estado_prendida_por_horas_y_la_habitacion VARCHAR,
    d16 VARCHAR, -- tiene abcd o numeros
    
    clave_17 VARCHAR,
    d17_tipo VARCHAR,
    kate_tiene_una_linda_cara_y_bonitos_ojos_ella VARCHAR,
    d17 VARCHAR, -- tiene abcd o numeros
    
    clave_18 VARCHAR,
    d18_tipo VARCHAR,
    julian_esta_escondido_detras_del_arbol_sin_moverse_el_es VARCHAR,
    d18 VARCHAR, -- tiene abcd o numeros
    
    total_d INT(3)

);
