#Carga de librerías
from __future__ import unicode_literals, print_function
import plac
import random
from pathlib import Path
import spacy
#from tqdm import tqdm
from spacy.util import minibatch, compounding

#Definición de identificadores de partes del discurso

TAG_MAP = {"N": {"pos": "NOUN"},
           "V": {"pos": "VERB"},
           "J": {"pos": "ADJ"},
           "D": {"pos": "ADV"},
           "SC": {"pos": "SCONJ"},
           "AX": {"pos": "AUX"},
           "DT": {"pos": "DET"},
           "CN": {"pos": "CONJ"},
           "ADP": {"pos": "ADP"},
           "PCT": {"pos": "PUNCT"},
           "PRN": {"pos": "PRON"},
           "P": {"pos": "PROPN"},
           "NM": {"pos": "NUM"},
           "PRT": {"POS": "PART"}
           }

#Palabras para entrenamiento
TRAIN_DATA = [
    ("El gato es amigo de ratón y perro", {"tags":['DT', 'N', 'AX', 'N', 'ADP', 'N', 'CN', 'N']}),
    ("por que las pelotas son un juguete o aparato de distracción por lo tanto no tienen vida solo en Toy Story así que como no tienen vida no pueden cantar", {"tags":['ADP', 'SC', 'DT', 'N', 'AX', 'DT', 'N', 'CN', 'N', 'ADP', 'N', 'ADP', 'DT', 'N', 'D', 'V', 'N', 'J', 'ADP', 'P', 'P', 'D', 'SC', 'SC', 'D', 'V', 'N', 'D', 'AX', 'V']}),
    ("rima", {"tags":['N']}),
    ("por que millonario canta", {"tags":['ADP', 'SC', 'J', 'V']}),
    ("por que al escucharse no tiene sentido", {"tags":['ADP', 'SC', 'ADP', 'V', 'D', 'V', 'N']}),
    ("la pelota salta no canta", {"tags":['DT', 'N', 'V', 'D', 'V']}),
    ("por que ninguna pelota cuando la rebotas no canta", {"tags":['ADP', 'SC', 'DT', 'N', 'SC', 'DT', 'V', 'D', 'V']}),
    ("pelota es una metáfora para referirse a alguien con las cualidades", {"tags":['N', 'AX', 'DT', 'N', 'ADP', 'N', 'ADP', 'PRN', 'ADP', 'DT', 'N']}),
    ("pelota no puede cantar", {"tags":['N', 'D', 'AX', 'V']}),
    ("que mi hermano en redondo y grita mucho", {"tags":['SC', 'DT', 'N', 'ADP', 'J', 'CN', 'V', 'D']}),
    ("que es chillón", {"tags":['SC', 'AX', 'J']}),
    ("el perro o el gato", {"tags":['DT', 'N', 'CN', 'DT', 'N']}),
    ("perro", {"tags":['N']}),
    ("estambre", {"tags":['N']}),
    ("el perro", {"tags":['DT', 'N']}),
    ("tu bello", {"tags":['DT', 'J']}),
    ("el perro o caballo", {"tags":['DT', 'N', 'CN', 'N']}),
    ("tu perro", {"tags":['DT', 'N']}),
    ("gato perro ratón", {"tags":['N', 'N', 'N']}),
    ("ratón", {"tags":['N']}),
    ("la rabo de conejo", {"tags":['DT', 'N', 'ADP', 'N']}),
    ("hámster", {"tags":['N']}),
    ("por que la soledad es un tesoro que se debe de aprovechar y usarse", {"tags":['ADP', 'SC', 'DT', 'N', 'AX', 'DT', 'N', 'PRN', 'PRN', 'AX', 'ADP', 'V', 'CN', 'V']}),
    ("por que la copa de la liga mx es de plata", {"tags":['ADP', 'SC', 'DT', 'N', 'ADP', 'DT', 'P', 'P', 'AX', 'ADP', 'N']}),
    ("por que un balín es como una pelota y es de color plata", {"tags":['ADP', 'SC', 'DT', 'N', 'AX', 'SC', 'DT', 'N', 'CN', 'AX', 'ADP', 'N', 'N']}),
    ("por que vale plata", {"tags":['ADP', 'SC', 'V', 'N']}),
    ("pelota padre", {"tags":['N', 'N']}),
    ("moneda por que en es como una pelota y es redonda y vale y tienes que esforzaste para eso cuando rebotas una pelota tienes que mover las manos entonces para ganar el dinero lo mismo tienes que mover las manos para lograr eso mm es lógico verdad me voy lentamente", {"tags":['N', 'ADP', 'SC', 'ADP', 'AX', 'SC', 'DT', 'N', 'CN', 'AX', 'J', 'CN', 'V', 'CN', 'V', 'SC', 'V', 'ADP', 'PRN', 'SC', 'V', 'DT', 'N', 'V', 'SC', 'V', 'DT', 'N', 'D', 'ADP', 'V', 'DT', 'N', 'DT', 'DT', 'V', 'SC', 'V', 'DT', 'N', 'ADP', 'V', 'PRN', 'N', 'AX', 'J', 'N', 'PRN', 'V', 'D']}),
    ("que como es plata parece moneda o suena como una moneda", {"tags":['SC', 'SC', 'AX', 'N', 'AX', 'N', 'CN', 'V', 'SC', 'DT', 'N']}),
    ("pelota de plata", {"tags":['N', 'ADP', 'N']}),
    ("creo que es una pelota color plata", {"tags":['V', 'SC', 'AX', 'DT', 'N', 'N', 'N']}),
    ("la luna tiene forma de pelota y es color plata", {"tags":['DT', 'N', 'V', 'N', 'ADP', 'N', 'CN', 'AX', 'N', 'N']}),
    ("mi papa es una pelota de plata porque el es el que genera mas plata dinero", {"tags":['DT', 'N', 'AX', 'DT', 'N', 'ADP', 'N', 'SC', 'DT', 'AX', 'DT', 'PRN', 'V', 'D', 'N', 'N']}),
    ("es redonda y tiene color plata", {"tags":['AX', 'J', 'CN', 'V', 'N', 'N']}),
    ("la luna por que es redonda y color como gris", {"tags":['DT', 'N', 'ADP', 'PRN', 'AX', 'J', 'CN', 'N', 'SC', 'N']}),
    ("algo que es de plata o que vale plata para ti", {"tags":['PRN', 'PRN', 'AX', 'ADP', 'N', 'CN', 'PRN', 'V', 'N', 'ADP', 'PRN']}),
    ("por que es de color plata", {"tags":['ADP', 'SC', 'AX', 'ADP', 'N', 'N']}),
    ("es una bola de color plata", {"tags":['AX', 'DT', 'N', 'ADP', 'N', 'N']}),
    ("es de el color plata", {"tags":['AX', 'ADP', 'DT', 'N', 'N']}),
    ("pues pelota de plata", {"tags":['SC', 'N', 'ADP', 'N']}),
    ("la luna es color plata y brilla", {"tags":['DT', 'N', 'AX', 'N', 'N', 'CN', 'N']}),
    ("qwewqe", {"tags":['P']}),
    ("hrtehtrjjrey", {"tags":['P']}),
    ("pues es una pelta color plata y mi chica", {"tags":['SC', 'AX', 'DT', 'J', 'N', 'N', 'CN', 'DT', 'N']}),
    ("pelota hecha de plata o color plata", {"tags":['N', 'J', 'ADP', 'N', 'CN', 'N', 'N']}),
    ("la luna es color plata", {"tags":['DT', 'N', 'AX', 'N', 'N']}),
    ("porque es una cosa hecha de metal y es color plata", {"tags":['SC', 'AX', 'DT', 'N', 'J', 'ADP', 'N', 'CN', 'AX', 'N', 'N']}),
    ("puse luna por que es redonda y su color le tira al plateado siendo así una metáfora", {"tags":['V', 'J', 'ADP', 'SC', 'AX', 'J', 'CN', 'DT', 'N', 'PRN', 'V', 'ADP', 'J', 'AX', 'D', 'DT', 'N']}),
    ("pelota fina", {"tags":['N', 'J']}),
    ("si una pelota de fuego es el sol la de plata es la luna por ser blanca", {"tags":['SC', 'DT', 'N', 'ADP', 'N', 'AX', 'DT', 'N', 'DT', 'ADP', 'N', 'AX', 'DT', 'N', 'ADP', 'AX', 'J']}),
    ("porque es blanca con gris y brilla la plata es mas o menos así", {"tags":['SC', 'AX', 'J', 'ADP', 'N', 'CN', 'V', 'DT', 'N', 'AX', 'D', 'CN', 'D', 'D']}),
    ("una pelota color plata", {"tags":['DT', 'N', 'N', 'N']}),
    ("la luna por que es redonda y de color plata", {"tags":['DT', 'N', 'ADP', 'PRN', 'AX', 'J', 'CN', 'ADP', 'N', 'N']}),
    ("la luna es circular y de color plata", {"tags":['DT', 'N', 'AX', 'V', 'CN', 'ADP', 'N', 'N']}),
    ("la luna tiene un color muy singular que hace que a veces la veamos de color plata", {"tags":['DT', 'N', 'V', 'DT', 'N', 'D', 'J', 'PRN', 'V', 'SC', 'ADP', 'N', 'PRN', 'V', 'ADP', 'N', 'N']}),
    ("alguien que es fuerte o mercurio color plata", {"tags":['PRN', 'PRN', 'AX', 'J', 'CN', 'J', 'N', 'N']}),
    ("Los amigos son muy valiosos, en mi opinión, como la plata, pero no se puede conseguir gratis y se puede aplicar una cicatriz a la misma, lo más importante antes de que puedas amar a un amigo. El oro significa que amarte a ti mismo es la primera cosa que debes hacer.", {"tags":['DT', 'N', 'AX', 'D', 'J', 'PCT', 'ADP', 'DT', 'N', 'PCT', 'SC', 'DT', 'N', 'PCT', 'CN', 'D', 'PRN', 'AX', 'V', 'J', 'CN', 'PRN', 'AX', 'V', 'DT', 'N', 'ADP', 'DT', 'PRN', 'PCT', 'DT', 'D', 'J', 'D', 'ADP', 'SC', 'AX', 'V', 'ADP', 'DT', 'N', 'PCT', 'DT', 'N', 'V', 'SC', 'V', 'ADP', 'PRN', 'PRN', 'AX', 'DT', 'J', 'N', 'PRN', 'AX', 'V', 'PCT']}),
    ("la luna se ve como de plata o color plata y brilla en la noche", {"tags":['DT', 'N', 'PRN', 'V', 'SC', 'ADP', 'N', 'CN', 'N', 'N', 'CN', 'V', 'ADP', 'DT', 'N']}),
    ("de Zacatecas", {"tags":['ADP', 'P']}),
    ("el cabello es de diferentes formas lacio chino crespo suave etc", {"tags":['DT', 'N', 'AX', 'ADP', 'DT', 'N', 'J', 'J', 'P', 'J', 'PCT']}),
    ("que se parece a Trevor", {"tags":['SC', 'PRN', 'V', 'ADP', 'P']}),
    ("nublosas", {"tags":['J']}),
    ("de leches", {"tags":['ADP', 'N']}),
    ("blanca", {"tags":['J']}),
    ("greñudo", {"tags":['J']}),
    ("picudo", {"tags":['J']}),
    ("crespo", {"tags":['P']}),
    ("vbsdhdsbhf invalida", {"tags":['P', 'J']}),
    ("lacio y largo", {"tags":['J', 'CN', 'J']}),
    ("esponjaditas grandes de diferentes figuras", {"tags":['J', 'J', 'ADP', 'DT', 'N']}),
    ("el cabello es de un color verde y es puntiagudo", {"tags":['DT', 'N', 'AX', 'ADP', 'DT', 'N', 'J', 'CN', 'AX', 'J']}),
    ("feqrg", {"tags":['P']}),
    ("con carne dentro y color como crema como amarillo y café mas o menos nombrándolo así y estas teclas no sirven", {"tags":['ADP', 'N', 'D', 'CN', 'N', 'SC', 'N', 'SC', 'J', 'CN', 'N', 'D', 'CN', 'D', 'J', 'D', 'CN', 'DT', 'N', 'D', 'V']}),
    ("carnuda", {"tags":['J']}),
    ("flores de un color extravagante", {"tags":['N', 'ADP', 'DT', 'N', 'J']}),
    ("las flores de oro son iguales a el rocío de una rosa que es y que no es una flor de oro si lo tengo delante de mi leyendo esta frase de amor que han pasado", {"tags":['DT', 'N', 'ADP', 'N', 'AX', 'J', 'ADP', 'DT', 'N', 'ADP', 'DT', 'N', 'PRN', 'AX', 'CN', 'SC', 'D', 'AX', 'DT', 'N', 'ADP', 'N', 'SC', 'PRN', 'V', 'D', 'ADP', 'DT', 'V', 'DT', 'N', 'ADP', 'N', 'PRN', 'AX', 'V']}),
    ("portas", {"tags":['V']}),
    ("brillosas", {"tags":['J']}),
    ("suave o rígida depende de tu ADN molecular", {"tags":['J', 'CN', 'J', 'V', 'ADP', 'DT', 'N', 'J']}),
    ("flores que brillan y que te llenan los ojos de alegría", {"tags":['N', 'PRN', 'V', 'CN', 'PRN', 'PRN', 'V', 'DT', 'N', 'ADP', 'N']}),
    ("flores color amarillo o dorado", {"tags":['N', 'N', 'J', 'CN', 'J']}),
    ("flores duros con bonitas colores", {"tags":['N', 'J', 'ADP', 'J', 'N']}),
    ("no por que los dientes son de marfil", {"tags":['D', 'ADP', 'SC', 'DT', 'N', 'AX', 'ADP', 'N']}),
    ("por brillan y los tiene blancos", {"tags":['ADP', 'V', 'CN', 'PRN', 'V', 'J']}),
    ("que las perlas brillan", {"tags":['SC', 'DT', 'N', 'V']}),
    ("que brillan y son blancos", {"tags":['SC', 'V', 'CN', 'AX', 'J']}),
    ("de pura de seda", {"tags":['ADP', 'J', 'ADP', 'N']}),
    ("seda", {"tags":['N']}),
    ("flores de oro", {"tags":['N', 'ADP', 'N']}),
    ("son flores color oro", {"tags":['AX', 'N', 'N', 'N']}),
    ("pues de oro perro", {"tags":['SC', 'ADP', 'N', 'N']}),
    ("son las flor de girasol", {"tags":['AX', 'DT', 'N', 'ADP', 'N']}),
    ("flores del color del oro", {"tags":['N', 'ADP', 'N', 'ADP', 'N']}),
    ("flores amarillo brillante", {"tags":['N', 'J', 'J']}),
    ("una hermana rica okay no es una hermana tierna amable etc", {"tags":['DT', 'N', 'J', 'ITJ', 'D', 'AX', 'DT', 'N', 'J', 'J', 'PCT']}),
    ("porque tal vez se llame candy", {"tags":['SC', 'N', 'N', 'PRN', 'V', 'P']}),
    ("efe", {"tags":['P']}),
    ("son como el mio arduamente intenso y sonrojadamente destenso", {"tags":['AX', 'SC', 'DT', 'N', 'D', 'J', 'CN', 'J', 'J']}),
    ("dulce linda amable", {"tags":['J', 'J', 'J']}),
    ("dulce linda y simpática", {"tags":['J', 'J', 'CN', 'J']}),
    ("linda dulce y tierna", {"tags":['J', 'J', 'CN', 'J']}),
    ("una mirada que puede enamorarte o asustarte", {"tags":['DT', 'N', 'PRN', 'AX', 'V', 'CN', 'V']}),
    ("una sonrisa muy fría u okay no es una sonrisa fingida", {"tags":['DT', 'N', 'D', 'J', 'CN', 'ITJ', 'D', 'AX', 'DT', 'N', 'J']}),
    ("como sin ganas de reírte", {"tags":['SC', 'ADP', 'N', 'ADP', 'V']}),
    ("r4fwrg", {"tags":['P']}),
    ("yes", {"tags":['P']}),
    ("muy fría casi sin notarse", {"tags":['D', 'J', 'D', 'ADP', 'V']}),
    ("tibia", {"tags":['J']}),
    ("Colgate", {"tags":['P']}),
    ("de flojera", {"tags":['ADP', 'N']}),
    ("no solo que vivas en Alaska", {"tags":['PRT', 'N', 'SC', 'J', 'ADP', 'P']}),
    ("cuando comes hielo y se te congela la boca", {"tags":['SC', 'V', 'N', 'CN', 'PRN', 'PRN', 'V', 'DT', 'N']}),
    ("blanca y fría", {"tags":['J', 'CN', 'N']}),
    ("sin ganas como de que esta fastidiado art no tiene autoestima ni moral quizá tenga problemas no quiere hablar con nadie y quiere su espacio", {"tags":['ADP', 'N', 'SC', 'ADP', 'SC', 'DT', 'J', 'P', 'D', 'V', 'N', 'CN', 'N', 'D', 'V', 'N', 'D', 'V', 'V', 'ADP', 'PRN', 'CN', 'V', 'DT', 'N']}),
    ("sonríes y te derrites", {"tags":['V', 'CN', 'PRN', 'V']}),
    ("bitter solor", {"tags":['P', 'P']}),
    ("ocurre que se da mas la vegetación y naturaleza", {"tags":['V', 'SC', 'PRN', 'V', 'D', 'DT', 'N', 'CN', 'N']}),
    ("ftrjhu4j", {"tags":['P']}),
    ("sol vacaciones y muchísimo calor", {"tags":['N', 'N', 'CN', 'J', 'N']}),
    ("viene Olaf y las mariposas y también las vacaciones", {"tags":['V', 'P', 'CN', 'DT', 'N', 'CN', 'D', 'DT', 'N']}),
    ("los días son intensos que ocurren con los días miles de preguntas y cientos de respuestas albergan las calles de la soledad albergan delante mío de la sinofena tercera mía dejar las preguntas para después y mirar los días y años de la pesadumbre pasar lentamente ya pues no de pude arreglar ni cambiar tal vida miserable autor marco Antonio Gutiérrez león", {"tags":['DT', 'N', 'AX', 'J', 'PRN', 'V', 'ADP', 'DT', 'N', 'NM', 'ADP', 'N', 'CN', 'NM', 'ADP', 'N', 'V', 'DT', 'N', 'ADP', 'DT', 'N', 'V', 'D', 'DT', 'ADP', 'DT', 'J', 'J', 'PRN', 'V', 'DT', 'N', 'ADP', 'D', 'CN', 'V', 'DT', 'N', 'CN', 'N', 'ADP', 'DT', 'N', 'V', 'D', 'D', 'SC', 'D', 'ADP', 'AX', 'V', 'CN', 'V', 'DT', 'N', 'J', 'N', 'P', 'P', 'P', 'P']}),
    ("porque el gobierno no nos da nuestros impuestos", {"tags":['SC', 'DT', 'N', 'D', 'PRN', 'V', 'DT', 'N']}),
    ("llueve a cántaros", {"tags":['V', 'ADP', 'D']}),
    ("es aburrido y tedioso como el Carol", {"tags":['AX', 'V', 'CN', 'J', 'SC', 'DT', 'P']}),
    ("dormiste y sonaste con los angelitos", {"tags":['V', 'CN', 'V', 'ADP', 'DT', 'N']}),
    ("juegos diversión pasamos todos en familia", {"tags":['N', 'N', 'V', 'PRN', 'ADP', 'N']}),
    ("que no me quiere y quiere que conozca más personas para que me lastimen así como David que me dijo que le gustaba y a los dos días su novia es Nicole maldito año porque tardas mucho en terminar", {"tags":['SC', 'D', 'PRN', 'V', 'CN', 'V', 'SC', 'V', 'D', 'N', 'ADP', 'SC', 'PRN', 'V', 'D', 'SC', 'P', 'SC', 'PRN', 'V', 'SC', 'PRN', 'V', 'CN', 'ADP', 'DT', 'NM', 'N', 'DT', 'N', 'AX', 'P', 'J', 'N', 'SC', 'V', 'D', 'ADP', 'V']}),
    ("mas tiempo libre en el día", {"tags":['D', 'N', 'J', 'ADP', 'DT', 'N']}),
    ("que deja los mas valioso que tienes todo va y viene", {"tags":['PRN', 'V', 'DT', 'D', 'J', 'SC', 'V', 'PRN', 'V', 'CN', 'V']}),
    ("que si tienes un problema y se solucionara y mas después vendrán tiempos mejores tiempo de felicidad", {"tags":['SC', 'SC', 'V', 'DT', 'N', 'CN', 'PRN', 'V', 'CN', 'D', 'D', 'V', 'N', 'J', 'N', 'ADP', 'N']}),
    ("que llego mi tío navidad", {"tags":['SC', 'V', 'DT', 'N', 'N']}),
    ("que ya es la fecha de navidad", {"tags":['SC', 'D', 'AX', 'DT', 'N', 'ADP', 'N']}),
    ("que ya es navidad", {"tags":['SC', 'D', 'AX', 'N']}),
    ("que la navidad a llegado al país", {"tags":['SC', 'DT', 'N', 'ADP', 'J', 'ADP', 'N']}),
    ("que la navidad ya llegó", {"tags":['SC', 'DT', 'N', 'D', 'V']}),
    ("cuando pones tu árbol y adornos y te comprar regalos tu papa", {"tags":['SC', 'V', 'DT', 'N', 'CN', 'N', 'CN', 'PRN', 'V', 'N', 'DT', 'N']}),
    ("que la navidad llegó", {"tags":['SC', 'DT', 'N', 'V']}),
    ("que es época de adviento", {"tags":['SC', 'AX', 'N', 'ADP', 'N']}),
    ("es la época de navidad", {"tags":['AX', 'DT', 'N', 'ADP', 'N']}),
    ("que los papás reyes están por llegar", {"tags":['SC', 'DT', 'N', 'N', 'AX', 'ADP', 'V']}),
    ("que navidad comienza", {"tags":['SC', 'N', 'V']}),
    ("que es navidad", {"tags":['SC', 'AX', 'N']}),
    ("es navidad", {"tags":['AX', 'N']}),
    ("creo que estoy confundido por que los segundos no tienen a las a no ser que te refieras a que los segundos pasan muy rápido y eso si que es verdad pero bueno creo que e llegado al final así que adiós cuidate", {"tags":['V', 'SC', 'AX', 'J', 'ADP', 'SC', 'DT', 'N', 'D', 'V', 'ADP', 'DT', 'ADP', 'D', 'AX', 'SC', 'PRN', 'V', 'ADP', 'SC', 'DT', 'N', 'V', 'D', 'J', 'CN', 'PRN', 'SC', 'SC', 'AX', 'N', 'CN', 'J', 'V', 'SC', 'CN', 'V', 'ADP', 'N', 'D', 'SC', 'V', 'V']}),
    ("siempre tendremos un día malo pero eso no significa que nuestra vida sera mala todos pasamos por malos momentos eso es parte de la vida la vida se trata de como podemos recibir golpes y seguir adelante se trata de esforzarse", {"tags":['D', 'V', 'DT', 'N', 'J', 'CN', 'PRN', 'D', 'V', 'SC', 'DT', 'N', 'V', 'J', 'PRN', 'V', 'ADP', 'J', 'N', 'PRN', 'AX', 'N', 'ADP', 'DT', 'N', 'DT', 'N', 'PRN', 'V', 'ADP', 'SC', 'AX', 'V', 'N', 'CN', 'V', 'D', 'PRN', 'V', 'ADP', 'N']}),
    ("que lo feo paso ahora viene lo chido feat Luis comunica", {"tags":['SC', 'DT', 'J', 'N', 'D', 'V', 'PRN', 'J', 'P', 'P', 'V']}),
    ("que el festejo mas importante del año ya llego", {"tags":['SC', 'DT', 'N', 'D', 'J', 'ADP', 'N', 'D', 'V']}),
    ("que la navidad llego", {"tags":['SC', 'DT', 'N', 'N']}),
    ("que la navidad ya llego", {"tags":['SC', 'DT', 'N', 'D', 'V']}),
    ("santa", {"tags":['P']}),
    ("que es tiempo de celebrar la navidad", {"tags":['SC', 'AX', 'N', 'ADP', 'V', 'DT', 'N']}),
    ("que llego la navidad", {"tags":['SC', 'V', 'DT', 'N']}),
    ("que la navidad esta por llegar", {"tags":['SC', 'DT', 'N', 'DT', 'ADP', 'V']}),
    ("ya es navidad", {"tags":['D', 'AX', 'N']}),
    ("que después de todo lo malo que sucedió el que escribió la frase tiene esperanza en un mejor futuro", {"tags":['SC', 'D', 'ADP', 'DT', 'DT', 'J', 'PRN', 'V', 'DT', 'PRN', 'V', 'DT', 'N', 'V', 'N', 'ADP', 'DT', 'J', 'N']}),
    ("que ha llegado la época de la navidad en la que como bien rico y mis papás me dan juguetes y la comida esta bien bien rica y me encanta el pavo por si querían saber", {"tags":['PRN', 'AX', 'V', 'DT', 'N', 'ADP', 'DT', 'N', 'ADP', 'DT', 'PRN', 'SC', 'N', 'J', 'CN', 'DT', 'N', 'PRN', 'V', 'N', 'CN', 'DT', 'N', 'DT', 'D', 'D', 'J', 'CN', 'PRN', 'V', 'DT', 'N', 'ADP', 'SC', 'V', 'V']}),
    ("el nacimiento de dios en la tierraque después de todo lo malo vendrán tiempos mejores con mas felicidades etc", {"tags":['DT', 'N', 'ADP', 'P', 'ADP', 'DT', 'N', 'D', 'ADP', 'DT', 'DT', 'J', 'V', 'N', 'J', 'ADP', 'D', 'N', 'PCT']}),
    ("y santa Claus bajo", {"tags":['CN', 'P', 'P', 'ADP']}),
    ("que ya es navidad o va a ser navidad", {"tags":['SC', 'D', 'AX', 'N', 'CN', 'AX', 'ADP', 'AX', 'N']}),
    ("que la navidad ya esta aquí", {"tags":['SC', 'DT', 'N', 'D', 'DT', 'D']}),
    ("estamos en época de navidad", {"tags":['AX', 'ADP', 'N', 'ADP', 'N']}),
    ("que por fin es navidad", {"tags":['SC', 'ADP', 'N', 'AX', 'N']}),
    ("que es hora de festejar la navidad", {"tags":['SC', 'AX', 'N', 'ADP', 'V', 'DT', 'N']}),
    ("que la navidad llego regalos comida familia o soledad hay de todo en este mundo", {"tags":['SC', 'DT', 'N', 'V', 'N', 'N', 'N', 'CN', 'N', 'AX', 'ADP', 'PRN', 'ADP', 'DT', 'N']}),
    ("que ya estamos en navidad presente", {"tags":['SC', 'D', 'AX', 'ADP', 'N', 'J']}),
    ("que es el día de navidad y habrá cena regalos etc", {"tags":['SC', 'AX', 'DT', 'N', 'ADP', 'N', 'CN', 'AX', 'N', 'N', 'PCT']}),
    ("que ya es tiempo de navidad y regalos y cosas así", {"tags":['SC', 'D', 'AX', 'N', 'ADP', 'N', 'CN', 'N', 'CN', 'N', 'D']}),
    ("hay mucho amor en la casa y esta toda mi familia conmigo y es divertido", {"tags":['AX', 'DT', 'N', 'ADP', 'DT', 'N', 'CN', 'DT', 'DT', 'DT', 'N', 'PRN', 'CN', 'AX', 'J']}),
    ("que llegó navidad", {"tags":['PRN', 'V', 'N']}),
    ("que la navidad ya esta", {"tags":['SC', 'DT', 'N', 'D', 'DT']}),
    ("que ha llegado el frio y pues también algunas personas a enfermarse", {"tags":['PRN', 'AX', 'V', 'DT', 'N', 'CN', 'SC', 'D', 'DT', 'N', 'ADP', 'V']}),
    ("año nuevo y llegan regalos", {"tags":['N', 'J', 'CN', 'V', 'N']}),
    ("que al fin es navidad", {"tags":['SC', 'ADP', 'N', 'AX', 'N']}),
    ("llega la época de navidad", {"tags":['V', 'DT', 'N', 'ADP', 'N']}),
    ("que ahora es navidad", {"tags":['SC', 'D', 'AX', 'N']}),
    ("que los segundos van tan rápido y que por mas rápido que van el no me ama solo ama a su novia pero que se puede esperar debí de hacer caso cuando Lilí me dijo que era solo un juguete pero no hay voy de mensa a caer en sus redes tan fácilmente deberían de darme un óscar por ilusionarme rápido y a el otro por ser un romper corazones excelente y ilusionador", {"tags":['SC', 'DT', 'N', 'V', 'D', 'J', 'CN', 'SC', 'ADP', 'D', 'J', 'PRN', 'V', 'DT', 'D', 'PRN', 'V', 'D', 'V', 'ADP', 'DT', 'N', 'CN', 'PRN', 'PRN', 'AX', 'V', 'V', 'ADP', 'V', 'N', 'SC', 'P', 'PRN', 'V', 'SC', 'AX', 'D', 'DT', 'N', 'CN', 'D', 'AX', 'AX', 'ADP', 'J', 'ADP', 'V', 'ADP', 'DT', 'N', 'D', 'D', 'AX', 'ADP', 'V', 'DT', 'N', 'ADP', 'N', 'J', 'CN', 'ADP', 'DT', 'PRN', 'ADP', 'AX', 'DT', 'V', 'N', 'J', 'CN', 'J']}),
    ("que ya esta aquí la navidad", {"tags":['SC', 'D', 'DT', 'D', 'DT', 'N']}),
    ("que ya es navidad o que las personas ya empezaron a decorar sus casas", {"tags":['SC', 'D', 'AX', 'N', 'CN', 'SC', 'DT', 'N', 'D', 'AX', 'ADP', 'V', 'DT', 'N']}),
    ("que empieza navidad", {"tags":['SC', 'V', 'N']}),
    ("santa Claus o regalos", {"tags":['P', 'P', 'CN', 'N']}),
    ("que el tiempo paso muy rápido que ya hace un año estábamos en navidad y pues llego rápido", {"tags":['SC', 'DT', 'N', 'J', 'D', 'J', 'SC', 'D', 'AX', 'DT', 'N', 'V', 'ADP', 'N', 'CN', 'SC', 'V', 'D']}),
    ("que aun faltan mas cosas buenas por venir", {"tags":['SC', 'D', 'V', 'D', 'N', 'J', 'ADP', 'V']}),
    ("que ya falta poco o ya es navidad", {"tags":['SC', 'D', 'V', 'D', 'CN', 'D', 'AX', 'N']}),
    ("que ya es la fecha de navidad o que ya se tiene espíritu navideño", {"tags":['SC', 'D', 'AX', 'DT', 'N', 'ADP', 'N', 'CN', 'PRN', 'D', 'PRN', 'V', 'N', 'J']}),
    ("llego la día mas feliz del año que todas las personas celebran", {"tags":['V', 'DT', 'N', 'D', 'J', 'ADP', 'N', 'PRN', 'DT', 'DT', 'N', 'V']}),
    ("el día de la navidad estaba aquí", {"tags":['DT', 'N', 'ADP', 'DT', 'N', 'AX', 'D']}),
    ("la es época de navidad", {"tags":['DT', 'AX', 'N', 'ADP', 'N']}),
    ("que la época de navidad ya esta y Jesús nace", {"tags":['SC', 'DT', 'N', 'ADP', 'N', 'D', 'DT', 'CN', 'P', 'V']}),
    ("que la navidad esta aquí", {"tags":['SC', 'DT', 'N', 'DT', 'D']}),
    ("que la fecha de navidad llego", {"tags":['SC', 'DT', 'N', 'ADP', 'N', 'N']}),
    ("que brillan", {"tags":['SC', 'V']}),
    ("que las estrellas brillan mas que ayer", {"tags":['SC', 'DT', 'N', 'V', 'D', 'PRN', 'D']}),
    ("que mis ojos o sus ojos son muy lindos", {"tags":['SC', 'DT', 'N', 'CN', 'DT', 'N', 'AX', 'D', 'J']}),
    ("puede tener ojos de color pero de miel no", {"tags":['AX', 'V', 'N', 'ADP', 'N', 'CN', 'ADP', 'N', 'D']}),
    ("por que Yolo", {"tags":['ADP', 'SC', 'P']}),
    ("que las estrellas brillan", {"tags":['SC', 'DT', 'N', 'V']}),
    ("por que brillan", {"tags":['ADP', 'SC', 'V']}),
    ("todo puede ser posible solo que los de miel serian solo en caricaturas una fantasía", {"tags":['PRN', 'AX', 'AX', 'J', 'J', 'SC', 'DT', 'ADP', 'N', 'V', 'D', 'ADP', 'N', 'DT', 'N']}),
    ("que son bellas y brillan tanto como si fueran de cristal", {"tags":['SC', 'AX', 'J', 'CN', 'V', 'D', 'SC', 'SC', 'AX', 'ADP', 'N']}),
    ("no porque las estrellas están a millones de kilómetros y son esferas de gas que se van consumiendo asta explotar y convertirse en ya sea una estrella de protones o una súper nova", {"tags":['D', 'SC', 'DT', 'N', 'AX', 'ADP', 'N', 'ADP', 'N', 'CN', 'AX', 'N', 'ADP', 'N', 'PRN', 'PRN', 'AX', 'V', 'J', 'V', 'CN', 'V', 'ADP', 'D', 'AX', 'DT', 'N', 'ADP', 'N', 'CN', 'DT', 'J', 'N']}),
    ("por que brillan y se podría decir que son de cristal", {"tags":['ADP', 'SC', 'V', 'CN', 'PRN', 'AX', 'V', 'SC', 'AX', 'ADP', 'N']}),
    ("por que la estrella brilla y se ve como cristal", {"tags":['ADP', 'SC', 'DT', 'N', 'V', 'CN', 'PRN', 'V', 'SC', 'N']}),
    ("por que las estrellas son muy posibles en hacerse como las de navidad", {"tags":['ADP', 'SC', 'DT', 'N', 'AX', 'D', 'J', 'ADP', 'N', 'SC', 'DT', 'ADP', 'N']}),
    ("sonando todo se puede amor mio", {"tags":['V', 'PRN', 'PRN', 'AX', 'N', 'J']}),
    ("porque puedes ejercitarte para tener unas piernas fuertes", {"tags":['SC', 'AX', 'V', 'ADP', 'V', 'DT', 'N', 'J']}),
    ("porque el orden de una materia no puede ser alterado por otra a menos de que ya exista un ADN que pueda alterar las moléculas humanas y metálicas", {"tags":['SC', 'DT', 'N', 'ADP', 'DT', 'N', 'D', 'AX', 'AX', 'V', 'ADP', 'PRN', 'ADP', 'D', 'ADP', 'SC', 'D', 'V', 'DT', 'N', 'PRN', 'AX', 'V', 'DT', 'N', 'J', 'CN', 'J']}),
    ("porque cuando describes alguien con ojos amarillo y café decimos ojos de miel", {"tags":['SC', 'SC', 'V', 'PRN', 'ADP', 'N', 'J', 'CN', 'N', 'V', 'N', 'ADP', 'N']}),
    ("pro que brillan", {"tags":['ADP', 'SC', 'V']}),
    ("porque esas brillan", {"tags":['SC', 'PRN', 'V']}),
    ("no porque las estrellas están hechas de pequeños asteroides", {"tags":['D', 'SC', 'DT', 'N', 'AX', 'J', 'ADP', 'J', 'N']}),
    ("porque el color miel sale del color café pero muy claro", {"tags":['SC', 'DT', 'N', 'N', 'V', 'ADP', 'N', 'N', 'CN', 'D', 'J']}),
    ("porque hay ojos color miel mas no hay ojos de miel", {"tags":['SC', 'AX', 'N', 'N', 'N', 'D', 'D', 'AX', 'N', 'ADP', 'N']}),
    ("porque es imposible tener ojos hechos de miel pero si color miel", {"tags":['SC', 'AX', 'J', 'V', 'N', 'J', 'ADP', 'N', 'CN', 'SC', 'N', 'N']}),
    ("porque decir ojos de miel es figurado nadie puede tener ojos hechos de miel", {"tags":['SC', 'V', 'N', 'ADP', 'N', 'AX', 'V', 'PRN', 'AX', 'V', 'N', 'J', 'ADP', 'N']}),
    ("wqb", {"tags":['P']}),
    ("una hoja doblada en varias partes", {"tags":['DT', 'N', 'J', 'ADP', 'DT', 'N']}),
    ("que si es posible yo he visto uno y tengo uno en casa no es mio pero lo tengo y lo he sentido", {"tags":['SC', 'SC', 'AX', 'J', 'PRN', 'AX', 'V', 'PRN', 'CN', 'V', 'PRN', 'ADP', 'N', 'D', 'AX', 'D', 'CN', 'PRN', 'V', 'CN', 'PRN', 'AX', 'V']}),
    ("la piel no puede ponerse en sobres o no que yo sepa", {"tags":['DT', 'N', 'D', 'AX', 'N', 'ADP', 'N', 'CN', 'D', 'SC', 'PRN', 'V']}),
    ("un papel que esta doblado en varias partes y se puede meter alguna carta", {"tags":['DT', 'N', 'PRN', 'DT', 'J', 'ADP', 'DT', 'N', 'CN', 'PRN', 'AX', 'V', 'DT', 'N']}),
    ("son pequeñas esferas que se encuentran en el mar en un animal llamado almeja", {"tags":['AX', 'J', 'N', 'PRN', 'PRN', 'V', 'ADP', 'DT', 'N', 'ADP', 'DT', 'N', 'J', 'N']}),
    ("por que es donde meten una carta para mandársela a una personas que están lejos", {"tags":['ADP', 'SC', 'AX', 'PRN', 'V', 'DT', 'N', 'ADP', 'V', 'ADP', 'DT', 'N', 'PRN', 'AX', 'D']}),
    ("las perlas se pueden hacer collar", {"tags":['DT', 'N', 'PRN', 'AX', 'V', 'V']}),
    ("por que lo mas común es hacer un vestido de un material suave tela", {"tags":['ADP', 'SC', 'DT', 'D', 'J', 'AX', 'V', 'DT', 'N', 'ADP', 'DT', 'N', 'J', 'V']}),
    ("que un zapato es como miel dulce", {"tags":['SC', 'DT', 'N', 'AX', 'SC', 'N', 'J']}),
    ("un zapato de miel", {"tags":['DT', 'N', 'ADP', 'N']}),
    ("que los zapatos estén creados de pura miel", {"tags":['SC', 'DT', 'N', 'AX', 'J', 'ADP', 'J', 'N']}),
    ("que yo dijo que no por lo que e vis ay de cuero", {"tags":['SC', 'PRN', 'V', 'SC', 'D', 'ADP', 'DT', 'PRN', 'CN', 'P', 'PRT', 'ADP', 'N']}),
    ("un zapato cubierto de miel", {"tags":['DT', 'N', 'J', 'ADP', 'N']}),
    ("que te largues", {"tags":['SC', 'PRN', 'V']}),
    ("todos lo meses de el año de Zacatecas", {"tags":['DT', 'DT', 'N', 'ADP', 'DT', 'N', 'ADP', 'P']}),
    ("que es un calendario hecho de zacate", {"tags":['SC', 'AX', 'DT', 'N', 'J', 'ADP', 'N']}),
    ("el ocnitrix", {"tags":['DT', 'P']}),
    ("escoba fina", {"tags":['N', 'J']}),
    ("escoba echa de cristal", {"tags":['N', 'V', 'ADP', 'N']}),
    ("escobas finas o delicadas", {"tags":['N', 'J', 'CN', 'J']}),
    ("miel con forma de zapatos", {"tags":['N', 'ADP', 'N', 'ADP', 'N']}),
    ("escobas hechas de cristal", {"tags":['N', 'J', 'ADP', 'N']}),
    ("escobas pero al lugar de los pelos es cristal", {"tags":['N', 'CN', 'ADP', 'N', 'ADP', 'DT', 'N', 'AX', 'J']}),
    ("escobas que están duras", {"tags":['N', 'PRN', 'AX', 'J']}),
    ("pues que pisaste miel", {"tags":['N', 'SC', 'V', 'N']}),
    ("que los zapato son de miel", {"tags":['SC', 'DT', 'N', 'AX', 'ADP', 'N']}),
    ("que pueden llenarse de miel", {"tags":['PRN', 'AX', 'N', 'ADP', 'N']}),
    ("zapato de cuero cubierto con miel", {"tags":['N', 'ADP', 'N', 'J', 'ADP', 'N']}),
    ("que no es posible hacer un calendario de zacate", {"tags":['SC', 'D', 'AX', 'J', 'V', 'DT', 'N', 'ADP', 'N']}),
    ("escobas muy delicadas", {"tags":['N', 'D', 'J']}),
    ("es una herramienta que tienes en casa para poder asearla casa limpiarla", {"tags":['AX', 'DT', 'N', 'PRN', 'V', 'ADP', 'N', 'ADP', 'V', 'V', 'V', 'V']}),
    ("calendario para bañarte", {"tags":['N', 'ADP', 'V']}),
    ("no no es posible es como si ella me amara", {"tags":['D', 'D', 'AX', 'J', 'AX', 'SC', 'SC', 'PRN', 'PRN', 'V']}),
    ("pueden ser creados parte de ellos con miel", {"tags":['AX', 'AX', 'V', 'N', 'ADP', 'PRN', 'ADP', 'N']}),
    ("no se puede hacer de zacate", {"tags":['D', 'PRN', 'AX', 'V', 'ADP', 'N']}),
    ("para bañarse", {"tags":['ADP', 'V']}),
    ("la miel se derrite y unos zapatos de miel no son muy cómodos", {"tags":['DT', 'N', 'PRN', 'V', 'CN', 'DT', 'N', 'ADP', 'N', 'D', 'AX', 'D', 'J']}),
    ("porque el zacate es algo que usas para bañarte", {"tags":['SC', 'DT', 'N', 'AX', 'PRN', 'PRN', 'V', 'ADP', 'V']}),
    ("si es posible que le caiga miel de abeja a tus zapatos pero muy improbable", {"tags":['SC', 'AX', 'J', 'SC', 'PRN', 'V', 'N', 'ADP', 'N', 'ADP', 'DT', 'N', 'CN', 'D', 'J']}),
    ("no es posible ya que una escoba debe estar hecha de fibras para que pueda recoger y empujar partículas de polvo", {"tags":['D', 'AX', 'J', 'D', 'SC', 'DT', 'N', 'AX', 'AX', 'J', 'ADP', 'N', 'ADP', 'SC', 'AX', 'V', 'CN', 'V', 'N', 'ADP', 'N']}),
    ("por que si es puede ser el zapato de miel", {"tags":['ADP', 'SC', 'SC', 'AX', 'AX', 'AX', 'DT', 'N', 'ADP', 'N']}),
    ("no es posible por que los zapatos de miel serian incómodos y pegajosos", {"tags":['D', 'AX', 'J', 'ADP', 'SC', 'DT', 'N', 'ADP', 'N', 'V', 'J', 'CN', 'J']}),
    ("porque el zacate es duro y grueso y porque nadie ocupa un calendario para bañarse también no se podría imprimir las letras en un zacate", {"tags":['SC', 'DT', 'N', 'AX', 'J', 'CN', 'J', 'CN', 'SC', 'PRN', 'V', 'DT', 'N', 'ADP', 'N', 'D', 'D', 'PRN', 'AX', 'V', 'DT', 'N', 'ADP', 'DT', 'N']}),
    ("pues por que no camino", {"tags":['SC', 'ADP', 'SC', 'D', 'N']}),
    ("porque un zacate es con lo que te tallas al bañarte a menos que tenga otro significado que no sepa y pues un calendario donde ves fechas", {"tags":['SC', 'DT', 'N', 'AX', 'ADP', 'DT', 'PRN', 'PRN', 'N', 'ADP', 'V', 'ADP', 'D', 'SC', 'V', 'DT', 'N', 'PRN', 'D', 'V', 'CN', 'SC', 'DT', 'N', 'PRN', 'V', 'N']}),
    ("por que no puedes hacer zapatos de miel ya que la miel es liquida", {"tags":['ADP', 'SC', 'D', 'AX', 'V', 'N', 'ADP', 'N', 'D', 'SC', 'DT', 'N', 'AX', 'N']}),
    ("porque no pueden ser literalmente de miel mas se puede ocupar como una expresión", {"tags":['SC', 'D', 'AX', 'AX', 'D', 'ADP', 'N', 'D', 'PRN', 'AX', 'V', 'SC', 'DT', 'N']}),
    ("porque no le veo ningún sentido a calendario de zacate", {"tags":['SC', 'D', 'PRN', 'V', 'DT', 'N', 'ADP', 'N', 'ADP', 'N']}),
    ("porque nadie dijo que tuviéramos que imprimirlo en la hierba seca, sólo dice que hay que crear una calandario, así que si la creas de una manera diferente, todo es posible.", {"tags":['SC', 'PRN', 'V', 'SC', 'V', 'SC', 'V', 'ADP', 'DT', 'N', 'J', 'PCT', 'D', 'V', 'SC', 'AX', 'SC', 'V', 'DT', 'N', 'PCT', 'D', 'SC', 'SC', 'DT', 'V', 'ADP', 'DT', 'N', 'J', 'PCT', 'PRN', 'AX', 'J', 'PCT']}),
    ("el carbón quema", {"tags":['DT', 'N', 'V']}),
    ("carbón ardiente es un pedazo de madera", {"tags":['N', 'J', 'AX', 'DT', 'N', 'ADP', 'N']}),
    ("que es lo que comes durante todo el día y lo dulce es normalmente en el desayuno por ejemplo el pan y en salado pues carnes mariscos", {"tags":['SC', 'AX', 'DT', 'PRN', 'V', 'ADP', 'DT', 'DT', 'N', 'CN', 'DT', 'J', 'AX', 'D', 'ADP', 'DT', 'N', 'ADP', 'N', 'DT', 'N', 'CN', 'ADP', 'N', 'SC', 'N', 'J']}),
    ("que no se entiende lo que escribes", {"tags":['SC', 'D', 'PRN', 'V', 'DT', 'PRN', 'V']}),
    ("que el carbón quema", {"tags":['SC', 'DT', 'N', 'V']}),
    ("que las estatuas de la isla de pascua", {"tags":['SC', 'DT', 'N', 'ADP', 'DT', 'N', 'ADP', 'N']}),
    ("un carbón son como piedras para que pendra y se quede prendida una fogata", {"tags":['DT', 'N', 'AX', 'SC', 'N', 'ADP', 'SC', 'V', 'CN', 'PRN', 'V', 'J', 'DT', 'N']}),
    ("por que algunas veces se nos puede ir la mano por eso es mejor medirla antes de agregarla", {"tags":['ADP', 'SC', 'DT', 'N', 'PRN', 'PRN', 'AX', 'V', 'DT', 'N', 'ADP', 'PRN', 'AX', 'J', 'N', 'D', 'ADP', 'V']}),
    ("que no es dulce bruh cier", {"tags":['SC', 'D', 'AX', 'J', 'P', 'P']}),
    ("comida que no es dulce que puedes comer o es de limón chile etc", {"tags":['N', 'PRN', 'D', 'AX', 'J', 'SC', 'AX', 'V', 'CN', 'AX', 'ADP', 'N', 'N', 'PCT']}),
    ("por que casi todas las esculturas son de hierro o piedra no hay mas a menos que seas rico y hagas una de hora", {"tags":['ADP', 'SC', 'D', 'DT', 'DT', 'N', 'AX', 'ADP', 'N', 'CN', 'N', 'D', 'AX', 'D', 'ADP', 'D', 'SC', 'AX', 'J', 'CN', 'V', 'PRN', 'ADP', 'N']}),
    ("si por que la modifican", {"tags":['SC', 'ADP', 'SC', 'PRN', 'V']}),
    ("si porque puede hacer que la comida sepa salado o por los ingredientes que tienen", {"tags":['SC', 'SC', 'AX', 'V', 'SC', 'DT', 'N', 'V', 'J', 'CN', 'ADP', 'DT', 'N', 'PRN', 'V']}),
    ("escencija", {"tags":['P']}),
    ("porque hay gente que por mas que intentes su letra no mejorara y jamas se le entenderá", {"tags":['SC', 'AX', 'N', 'PRN', 'ADP', 'D', 'SC', 'V', 'DT', 'N', 'D', 'V', 'CN', 'N', 'PRN', 'PRN', 'V']}),
    ("si por que en las plazas centro casa y lugares turísticos al igual que en museos las ahí", {"tags":['SC', 'ADP', 'SC', 'ADP', 'DT', 'N', 'N', 'N', 'CN', 'N', 'J', 'ADP', 'J', 'SC', 'ADP', 'N', 'DT', 'D']}),
    ("si ya que da a entender que no solo hay esculturas de metal bronceo plata u incluso oro sino que variedad es extensa", {"tags":['SC', 'D', 'SC', 'AX', 'ADP', 'AX', 'SC', 'PRT', 'N', 'AX', 'N', 'ADP', 'N', 'N', 'N', 'CN', 'D', 'N', 'CN', 'SC', 'N', 'AX', 'J']}),
    ("por ay muchas y mas grandes", {"tags":['ADP', 'V', 'DT', 'CN', 'N', 'J']}),
    ("si porque así como hay esculturas de bronce plata oro puede a ver de piedra y de mucho mas", {"tags":['SC', 'SC', 'D', 'SC', 'AX', 'N', 'ADP', 'N', 'N', 'N', 'AX', 'ADP', 'V', 'ADP', 'N', 'CN', 'ADP', 'D', 'D']}),
    ("si por que cuando haces fogatas o lumbre le pones carbón y arde", {"tags":['SC', 'ADP', 'SC', 'SC', 'V', 'N', 'CN', 'V', 'PRN', 'V', 'N', 'CN', 'V']}),
    ("porque en personas se pueden equivocar y echar sal marina para que sepa así", {"tags":['SC', 'ADP', 'N', 'PRN', 'AX', 'V', 'CN', 'V', 'N', 'J', 'ADP', 'SC', 'V', 'D']}),
    ("porque a veces se te olvida y le pones mas de la necesaria", {"tags":['SC', 'ADP', 'N', 'PRN', 'PRN', 'V', 'CN', 'PRN', 'V', 'D', 'ADP', 'DT', 'N']}),
    ("un abrazo dice mas que mas mil palabras", {"tags":['DT', 'N', 'V', 'D', 'SC', 'D', 'NM', 'N']}),
    ("que no importa como des el abrazo el valor no cambia", {"tags":['SC', 'D', 'V', 'SC', 'V', 'DT', 'N', 'DT', 'N', 'D', 'V']}),
    ("que te abrazan sin apretarte", {"tags":['SC', 'PRN', 'V', 'ADP', 'V']}),
    ("Donald Trump", {"tags":['P', 'P']}),
    ("que los abrazos que te dan o das son suaves que no son fuertes", {"tags":['SC', 'DT', 'N', 'PRN', 'PRN', 'V', 'CN', 'V', 'AX', 'J', 'PRN', 'D', 'AX', 'J']}),
    ("abrazo no tan fuerte", {"tags":['N', 'D', 'D', 'J']}),
    ("que la persona es tan cruel que no sabe apreciar a alguien mas sino que solo se interesa en el y en su vida que no tanto tiempo para pensar en el daño que lesa hace alas personas que lo quieren o lo aprecian", {"tags":['SC', 'DT', 'N', 'AX', 'D', 'J', 'SC', 'D', 'V', 'V', 'ADP', 'PRN', 'D', 'CN', 'SC', 'D', 'PRN', 'V', 'ADP', 'DT', 'CN', 'ADP', 'DT', 'N', 'PRN', 'D', 'DT', 'N', 'ADP', 'V', 'ADP', 'DT', 'N', 'PRN', 'V', 'AX', 'N', 'N', 'PRN', 'PRN', 'V', 'CN', 'PRN', 'V']}),
    ("pues que tiene su alma muy fuerte perro", {"tags":['N', 'SC', 'V', 'DT', 'N', 'D', 'J', 'N']}),
    ("mm pues una una alma de hierro o sea dura", {"tags":['P', 'SC', 'DT', 'DT', 'N', 'ADP', 'N', 'CN', 'AX', 'J']}),
    ("una alma a la que no le duele nada", {"tags":['DT', 'N', 'ADP', 'DT', 'PRN', 'D', 'PRN', 'V', 'PRN']}),
    ("que no hay almas de hierro mas adelante las podrían crear", {"tags":['SC', 'D', 'AX', 'N', 'ADP', 'N', 'D', 'D', 'DT', 'AX', 'V']}),
    ("indea", {"tags":['P']}),
    ("si por que hay gente muy cruel como Hitler que tenia un alma de hierro era muy cruel", {"tags":['SC', 'ADP', 'SC', 'AX', 'N', 'D', 'J', 'SC', 'P', 'SC', 'V', 'DT', 'N', 'ADP', 'N', 'AX', 'D', 'J']}),
    ("por que las al mas no se pueden tocar", {"tags":['ADP', 'SC', 'DT', 'ADP', 'D', 'D', 'PRN', 'AX', 'V']}),
    ("sor no descansarlos", {"tags":['P', 'D', 'V']}),
    ("si por que hay personas alas que no les gusta que las abrasen fuerte", {"tags":['SC', 'ADP', 'SC', 'AX', 'N', 'J', 'PRN', 'D', 'PRN', 'V', 'SC', 'DT', 'V', 'J']}),
    ("depende de tus fuerzas", {"tags":['V', 'ADP', 'DT', 'N']}),
    ("porque he visto a Donald Trump", {"tags":['SC', 'AX', 'V', 'ADP', 'P', 'P']}),
    ("porque aquel que ha perdido mucho y ademas ha resistido es porque el tiene mucha fuerza interior", {"tags":['SC', 'PRN', 'PRN', 'AX', 'V', 'D', 'CN', 'D', 'AX', 'V', 'AX', 'SC', 'DT', 'V', 'DT', 'N', 'J']}),
    ("no por que mas que una persona sea mala también tiene sentimientos", {"tags":['D', 'ADP', 'SC', 'D', 'SC', 'DT', 'N', 'AX', 'J', 'D', 'V', 'N']}),
    ("por que por mas que una persona sea mala todos los seres humanos tenemos sentimientos", {"tags":['ADP', 'SC', 'ADP', 'D', 'SC', 'DT', 'N', 'AX', 'J', 'DT', 'DT', 'N', 'J', 'V', 'N']}),
    ("no es posible por que el alma es transparente a menos que digas mi alama es de hierro", {"tags":['D', 'AX', 'J', 'ADP', 'SC', 'DT', 'N', 'AX', 'J', 'ADP', 'D', 'SC', 'V', 'DT', 'N', 'AX', 'ADP', 'N']}),
    ("si llega a pasarnos a todas las personas mas si eres muy estresante", {"tags":['SC', 'V', 'ADP', 'V', 'ADP', 'DT', 'DT', 'N', 'D', 'SC', 'AX', 'D', 'J']}),
    ("porque se pu", {"tags":['SC', 'PRN', 'P']}),
    ("una banqueta no puede abrigarte", {"tags":['DT', 'N', 'D', 'AX', 'V']}),
    ("calceta dura", {"tags":['N', 'J']}),
    ("los lapices sin sabor no son mas que lapices ordinarios en cambio el lápiz del sabor solo se muestran ante verdaderos escritores y a personas cultas del arte", {"tags":['DT', 'N', 'ADP', 'N', 'D', 'AX', 'J', 'SC', 'N', 'J', 'ADP', 'N', 'DT', 'N', 'ADP', 'N', 'J', 'PRN', 'V', 'ADP', 'J', 'N', 'CN', 'ADP', 'N', 'J', 'ADP', 'N']}),
    ("que el lápiz no tiene sabor", {"tags":['SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("que un lápiz no es de sabor", {"tags":['SC', 'DT', 'N', 'D', 'AX', 'ADP', 'N']}),
    ("que los lápiz no tienen sabor", {"tags":['SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("que el lápiz no sabe a nada", {"tags":['SC', 'DT', 'N', 'D', 'V', 'ADP', 'PRN']}),
    ("que el lápiz esta hecho de madera y la madera tiene sabor", {"tags":['SC', 'DT', 'N', 'DT', 'N', 'ADP', 'N', 'CN', 'DT', 'N', 'V', 'N']}),
    ("plata mineral", {"tags":['N', 'J']}),
    ("que el lápiz no tiene sabor pero la mayoría de los lápices tienen sabor por que viene de la madera después le ponen como pintura y eso le da como sabor feo pero tiene sabor", {"tags":['SC', 'DT', 'N', 'D', 'V', 'N', 'CN', 'DT', 'N', 'ADP', 'DT', 'N', 'V', 'N', 'ADP', 'PRN', 'V', 'ADP', 'DT', 'N', 'D', 'PRN', 'V', 'SC', 'N', 'CN', 'PRN', 'PRN', 'V', 'SC', 'N', 'J', 'CN', 'V', 'N']}),
    ("lápiz sin punta", {"tags":['N', 'ADP', 'N']}),
    ("que hay una cosa con la que se hace el lápiz que o tiene sabor", {"tags":['SC', 'AX', 'DT', 'N', 'ADP', 'DT', 'PRN', 'PRN', 'V', 'DT', 'N', 'PRN', 'CN', 'V', 'N']}),
    ("que el lápiz no escribe pues no le puede usar", {"tags":['SC', 'DT', 'N', 'D', 'V', 'SC', 'D', 'PRN', 'AX', 'V']}),
    ("lápiz con un sabor ejemplo fresa", {"tags":['N', 'ADP', 'DT', 'N', 'N', 'J']}),
    ("nada", {"tags":['PRN']}),
    ("calceta color plateada", {"tags":['N', 'N', 'J']}),
    ("que la calceta es color plata", {"tags":['SC', 'DT', 'N', 'AX', 'N', 'N']}),
    ("bueno pues una calceta color plata", {"tags":['J', 'SC', 'DT', 'N', 'N', 'N']}),
    ("lápiz que no sabe a nada si lo pruebas", {"tags":['N', 'SC', 'D', 'V', 'ADP', 'PRN', 'SC', 'PRN', 'N']}),
    ("que el lápiz no pinta bien", {"tags":['SC', 'DT', 'N', 'D', 'V', 'D']}),
    ("sabe a lo que a tocado ese lápiz", {"tags":['V', 'ADP', 'DT', 'PRN', 'ADP', 'J', 'DT', 'N']}),
    ("metafóricamente el lápiz no dibuja con el sabor necesario para transmitir algo", {"tags":['V', 'DT', 'N', 'D', 'V', 'ADP', 'DT', 'N', 'J', 'ADP', 'V', 'PRN']}),
    ("lápiz amargo", {"tags":['N', 'J']}),
    ("que el lápiz no pinta", {"tags":['SC', 'DT', 'N', 'D', 'V']}),
    ("que hay lápiz que no tienen sabor y ay otros que si tienen sabor", {"tags":['SC', 'AX', 'N', 'SC', 'D', 'V', 'N', 'CN', 'ITJ', 'PRN', 'PRN', 'SC', 'V', 'N']}),
    ("calceta color plata", {"tags":['N', 'N', 'N']}),
    ("calceta hecha de plata", {"tags":['N', 'J', 'ADP', 'N']}),
    ("por que todo tiene sabor color y olor por mas mínimo que sea", {"tags":['ADP', 'SC', 'PRN', 'V', 'N', 'N', 'CN', 'N', 'ADP', 'D', 'J', 'SC', 'AX']}),
    ("lápiz que no sabe a nada", {"tags":['N', 'SC', 'D', 'V', 'ADP', 'PRN']}),
    ("el lápiz tiene sabor de lo que esta hecho", {"tags":['DT', 'N', 'V', 'N', 'ADP', 'DT', 'PRN', 'DT', 'N']}),
    ("que el lápiz no pinta bien o su color no es bueno", {"tags":['SC', 'DT', 'N', 'D', 'V', 'D', 'CN', 'DT', 'N', 'D', 'AX', 'J']}),
    ("calceta hecha con plata", {"tags":['N', 'J', 'ADP', 'N']}),
    ("que el lápiz no sabe a nada si lo muerdes", {"tags":['SC', 'DT', 'N', 'D', 'V', 'ADP', 'PRN', 'SC', 'PRN', 'V']}),
    ("que el lápiz no tiene ningún sabor si te lo metes en la boca", {"tags":['SC', 'DT', 'N', 'D', 'V', 'DT', 'N', 'SC', 'PRN', 'PRN', 'V', 'ADP', 'DT', 'N']}),
    ("si porque dios creo todo el mundo", {"tags":['SC', 'SC', 'P', 'V', 'DT', 'DT', 'N']}),
    ("no no", {"tags":['D', 'D']}),
    ("no es posible por que los lápiz no tienen sabor", {"tags":['D', 'AX', 'J', 'ADP', 'SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("porque cuando muerdes un lápiz va a tener a fuerzas un sabor ni modo que la madera no tenga un sabor", {"tags":['SC', 'SC', 'V', 'DT', 'N', 'AX', 'ADP', 'V', 'ADP', 'N', 'DT', 'N', 'CN', 'N', 'SC', 'DT', 'N', 'D', 'V', 'DT', 'N']}),
    ("no por que todos los materiales con los que elaboran el lápiz tienen algún sabor", {"tags":['D', 'ADP', 'SC', 'DT', 'DT', 'N', 'ADP', 'DT', 'PRN', 'V', 'DT', 'N', 'V', 'DT', 'N']}),
    ("es para escribir", {"tags":['AX', 'ADP', 'V']}),
    ("no por que el lápiz no tiene sabor", {"tags":['D', 'ADP', 'SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("que yo sepa no existen calcetines de plata", {"tags":['SC', 'PRN', 'V', 'D', 'V', 'N', 'ADP', 'N']}),
    ("si es posible porque todo tiene sabor y el lápiz también", {"tags":['SC', 'AX', 'J', 'SC', 'PRN', 'V', 'N', 'CN', 'DT', 'N', 'D']}),
    ("si porque mi lápiz es así", {"tags":['SC', 'SC', 'DT', 'N', 'AX', 'D']}),
    ("pues creo que no porque pues una calceta no puede ser hecha de plata menos que la rellenes de plata", {"tags":['SC', 'V', 'SC', 'D', 'SC', 'SC', 'DT', 'N', 'D', 'AX', 'AX', 'V', 'ADP', 'N', 'D', 'SC', 'DT', 'V', 'ADP', 'N']}),
    ("porque el lápiz no sirve", {"tags":['SC', 'DT', 'N', 'D', 'V']}),
    ("porque lamo los lapices", {"tags":['SC', 'V', 'DT', 'N']}),
    ("no es posible porque el autor es el que transmite el sentimiento no el lápiz", {"tags":['D', 'AX', 'J', 'SC', 'DT', 'N', 'AX', 'DT', 'PRN', 'V', 'DT', 'N', 'D', 'DT', 'N']}),
    ("por que un lápiz pues tiene un sabor a madera", {"tags":['ADP', 'SC', 'DT', 'N', 'SC', 'V', 'DT', 'N', 'ADP', 'N']}),
    ("por que ningún lápiz tiene sabor si no son de dulce", {"tags":['ADP', 'SC', 'DT', 'N', 'V', 'N', 'SC', 'D', 'AX', 'ADP', 'N']}),
    ("porque puedes decir cosas si sentido no se refiere que el lápiz tenga sabor o no", {"tags":['SC', 'AX', 'V', 'N', 'SC', 'N', 'D', 'PRN', 'V', 'SC', 'DT', 'N', 'V', 'N', 'CN', 'D']}),
    ("no por que el lápiz no tienen sabor", {"tags":['D', 'ADP', 'SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("si por que los lápiz no tienen sabor", {"tags":['SC', 'ADP', 'SC', 'DT', 'N', 'D', 'V', 'N']}),
    ("no por que un lápiz esta hecho para escribir no para chupar", {"tags":['D', 'ADP', 'SC', 'DT', 'N', 'DT', 'N', 'ADP', 'V', 'D', 'ADP', 'V']}),
    ("porque te va a hacer sentir con mas confianza en ti misma", {"tags":['SC', 'PRN', 'AX', 'ADP', 'AX', 'V', 'ADP', 'D', 'N', 'ADP', 'PRN', 'DT']}),
    ("por que yo tengo calcetas color plata", {"tags":['ADP', 'SC', 'PRN', 'V', 'N', 'N', 'N']}),
    ("si el lápiz esta hecho de madera y la madera tiene sabor", {"tags":['SC', 'DT', 'N', 'DT', 'N', 'ADP', 'N', 'CN', 'DT', 'N', 'V', 'N']}),
    ("no porque si la calceta sera de plata nadie va a poder usarlo", {"tags":['D', 'SC', 'SC', 'DT', 'N', 'V', 'ADP', 'N', 'PRN', 'AX', 'ADP', 'AX', 'V']}),
    ("porque si muerdes un lápiz no va a saber a nada", {"tags":['SC', 'SC', 'V', 'DT', 'N', 'D', 'AX', 'ADP', 'V', 'ADP', 'PRN']}),
    ("a que una silla ya se desocupo", {"tags":['ADP', 'SC', 'DT', 'N', 'D', 'PRN', 'V']}),
    ("que la silla ya llego para que esperes y esperes algo sentada en ella", {"tags":['SC', 'DT', 'N', 'D', 'V', 'ADP', 'SC', 'V', 'CN', 'V', 'D', 'J', 'ADP', 'PRN']}),
    ("porque llego tu novia a tu casa", {"tags":['SC', 'PRN', 'J', 'N', 'ADP', 'DT', 'N']}),
    ("la cebolla llega a las manos del cachador después de un excelente lanzamiento por parte del pichador", {"tags":['DT', 'N', 'V', 'ADP', 'DT', 'N', 'ADP', 'N', 'D', 'ADP', 'DT', 'J', 'N', 'ADP', 'N', 'ADP', 'J']}),
    ("que cala mucho cuando picas", {"tags":['SC', 'V', 'D', 'SC', 'N']}),
    ("una m mccosciuspu", {"tags":['DT', 'N', 'P']}),
    ("que los de DHL te trajeron una silla", {"tags":['SC', 'DT', 'ADP', 'P', 'PRN', 'V', 'DT', 'N']}),
    ("el sol y el Hitler", {"tags":['DT', 'N', 'CN', 'DT', 'P']}),
    ("porque en este planeta el valor que mas se sigue es la flojera", {"tags":['SC', 'ADP', 'DT', 'N', 'DT', 'N', 'PRN', 'D', 'PRN', 'V', 'AX', 'DT', 'N']}),
    ("porque Liverpool te puede traer una silla", {"tags":['SC', 'P', 'PRN', 'AX', 'V', 'DT', 'N']}),
    ("que se las anel viado", {"tags":['SC', 'PRN', 'DT', 'P', 'J']}),
    ("que comes cebolla", {"tags":['SC', 'V', 'N']}),
    ("pues como cala es muy fuerte para ti", {"tags":['SC', 'SC', 'V', 'AX', 'D', 'J', 'ADP', 'PRN']}),
    ("por que yolo", {"tags":['ADP', 'SC', 'P']}),
    ("pelota cebolla", {"tags":['N', 'N']}),
    ("por que esta escrito en la biblia", {"tags":['ADP', 'SC', 'DT', 'N', 'ADP', 'DT', 'N']}),
    ("nod", {"tags":['P']}),
    ("porque no te bañaste o no cepillaste los dientes", {"tags":['SC', 'D', 'PRN', 'V', 'CN', 'D', 'V', 'DT', 'N']}),
    ("porque huele fuerte", {"tags":['SC', 'V', 'J']}),
    ("que Liverpool ya trajo su silla", {"tags":['SC', 'P', 'D', 'V', 'DT', 'N']}),
    ("cuando faltan traen mas", {"tags":['SC', 'V', 'V', 'D']}),
    ("si porque cuando partes cebolla lloras", {"tags":['SC', 'SC', 'SC', 'N', 'V', 'V']}),
    ("por que empiezas a cortar la cebolla y lloras", {"tags":['ADP', 'SC', 'AX', 'ADP', 'V', 'DT', 'N', 'CN', 'V']}),
    ("si porque cala en los ojos", {"tags":['SC', 'SC', 'V', 'ADP', 'DT', 'N']}),
    ("llego en las compras", {"tags":['V', 'ADP', 'DT', 'N']}),
    ("si por que cuando la avientas roda entonces puede llegar a ti", {"tags":['SC', 'ADP', 'SC', 'SC', 'DT', 'V', 'V', 'D', 'AX', 'V', 'ADP', 'PRN']}),
    ("por que un orno no tiene movilidad propia", {"tags":['ADP', 'SC', 'DT', 'N', 'D', 'V', 'N', 'J']}),
    ("si ya desocupo", {"tags":['SC', 'D', 'V']}),
    ("que los hornos de están moviendo mas cerca uno del otro", {"tags":['SC', 'DT', 'N', 'ADP', 'AX', 'V', 'D', 'D', 'PRN', 'ADP', 'PRN']}),
    ("porque son atletas perro", {"tags":['SC', 'AX', 'N', 'N']}),
    ("que pueden estar por lo aires", {"tags":['PRN', 'AX', 'V', 'ADP', 'DT', 'N']}),
    ("el tren transporta gente", {"tags":['DT', 'N', 'V', 'N']}),
    ("que las personas que son atletas pues corren y deben tener la habilidad para hacerlo e ir mejorando cada día mas", {"tags":['SC', 'DT', 'N', 'PRN', 'AX', 'N', 'SC', 'V', 'CN', 'AX', 'V', 'DT', 'N', 'ADP', 'V', 'CN', 'AX', 'V', 'DT', 'N', 'D']}),
    ("que el ave vuela", {"tags":['SC', 'DT', 'N', 'V']}),
    ("que una gaviota ave vuela", {"tags":['SC', 'DT', 'N', 'N', 'V']}),
    ("que el tren esta transportándose", {"tags":['SC', 'DT', 'N', 'DT', 'V']}),
    ("si perro", {"tags":['SC', 'N']}),
    ("Minecraft", {"tags":['P']}),
    ("por que en ellos viajan personas y ellos igual perro", {"tags":['ADP', 'SC', 'ADP', 'PRN', 'V', 'N', 'CN', 'PRN', 'J', 'N']}),
    ("así es como trabaja el tren", {"tags":['D', 'AX', 'SC', 'V', 'DT', 'N']}),
    ("porque gente como Usain Bolt existen", {"tags":['SC', 'N', 'SC', 'P', 'P', 'V']}),
    ("todos tienen el derecho a la libertad el ave volando es un símbolo de libertad mundial", {"tags":['PRN', 'V', 'DT', 'N', 'ADP', 'DT', 'N', 'DT', 'N', 'V', 'AX', 'DT', 'N', 'ADP', 'N', 'J']}),
    ("si y mas si es atleta por que ellos se especializan en eso", {"tags":['SC', 'CN', 'D', 'SC', 'AX', 'N', 'ADP', 'SC', 'PRN', 'PRN', 'V', 'ADP', 'PRN']}),
    ("por que así las hizo dios", {"tags":['ADP', 'SC', 'D', 'PRN', 'V', 'P']}),
    ("por que eyaqs debe volar", {"tags":['ADP', 'SC', 'P', 'AX', 'V']}),
    ("si porque alguna personas usan el tren para poder trasladarse de un lugar a otro", {"tags":['SC', 'SC', 'DT', 'N', 'V', 'DT', 'N', 'ADP', 'AX', 'V', 'ADP', 'DT', 'N', 'ADP', 'PRN']}),
    ("si porque tu te mueves y corres mas los atletas", {"tags":['SC', 'SC', 'DT', 'PRN', 'V', 'CN', 'V', 'D', 'DT', 'N']}),
    ("si eres atleta corres", {"tags":['SC', 'AX', 'N', 'V']}),
    ("que pongan mas tiempo en la escuela", {"tags":['SC', 'V', 'D', 'N', 'ADP', 'DT', 'N']}),
    ("que la ya va a ser la noche y va a empezar a oscurecerse", {"tags":['SC', 'PRN', 'D', 'AX', 'ADP', 'AX', 'DT', 'N', 'CN', 'AX', 'ADP', 'V', 'ADP', 'V']}),
    ("que es ora de dormir en tu colchón spring air", {"tags":['SC', 'AX', 'AX', 'ADP', 'V', 'ADP', 'J', 'N', 'P', 'P']}),
    ("que cobos corre", {"tags":['SC', 'P', 'V']}),
    ("que es mas que suficiente el tiempo", {"tags":['SC', 'AX', 'D', 'SC', 'J', 'DT', 'N']}),
    ("entre mas tardes mas tiempo necesitaras", {"tags":['ADP', 'D', 'N', 'D', 'N', 'J']}),
    ("siper", {"tags":['P']}),
    ("por que si te tardas el tiempo te alcanza ejemplo Ana tiene que salir a las tres y son las dos y media y se tarda jugando media hora entonces el tiempo la alcanza por que ya son las tres", {"tags":['ADP', 'SC', 'SC', 'PRN', 'V', 'DT', 'N', 'PRN', 'V', 'N', 'P', 'V', 'SC', 'V', 'ADP', 'DT', 'NM', 'CN', 'AX', 'DT', 'NM', 'CN', 'NM', 'CN', 'PRN', 'AX', 'V', 'NM', 'N', 'D', 'DT', 'N', 'DT', 'N', 'ADP', 'SC', 'D', 'AX', 'DT', 'NM']}),
    ("si por que en la biblia", {"tags":['SC', 'ADP', 'SC', 'ADP', 'DT', 'N']}),
    ("porque el día dura 12 horas y la noche 12 horas", {"tags":['SC', 'DT', 'N', 'V', 'NM', 'N', 'CN', 'DT', 'N', 'NM', 'N']}),
    ("es posible porque lo veo todos los días y me duermo bien rico y se siente delicioso y ademas me despiertan demasiado temprano para ir a la escuela en la que nos ponen encuestas bien chidas como esta se murió Robin Williams", {"tags":['AX', 'J', 'SC', 'PRN', 'V', 'DT', 'DT', 'N', 'CN', 'PRN', 'V', 'D', 'J', 'CN', 'PRN', 'V', 'J', 'CN', 'J', 'PRN', 'V', 'D', 'J', 'ADP', 'V', 'ADP', 'DT', 'N', 'ADP', 'DT', 'PRN', 'PRN', 'V', 'N', 'D', 'J', 'SC', 'PRN', 'PRN', 'V', 'P', 'P']}),
    ("por que sabiéndote organizar si te alcanza el tiempo", {"tags":['ADP', 'SC', 'V', 'AX', 'SC', 'PRN', 'V', 'DT', 'N']}),
    ("si por el ejemplo que di hace rato", {"tags":['SC', 'ADP', 'DT', 'N', 'PRN', 'V', 'V', 'N']}),
    ("por que el planeta tierra esta en constante rotación por lo que llega la noche", {"tags":['ADP', 'SC', 'DT', 'N', 'N', 'DT', 'ADP', 'J', 'N', 'ADP', 'DT', 'PRN', 'V', 'DT', 'N']}),
    ("si es posible porque la frase es usada para referirse a que el tiempo es suficiente", {"tags":['SC', 'AX', 'J', 'SC', 'DT', 'N', 'AX', 'V', 'ADP', 'V', 'ADP', 'SC', 'DT', 'N', 'AX', 'J']}),
    ("es una expresión muy conocida ademas tiene sentido tal y como lo dices", {"tags":['AX', 'DT', 'N', 'D', 'J', 'D', 'V', 'N', 'N', 'CN', 'SC', 'PRN', 'V']}),
    ("porque mientras mas tarde es mas noche es", {"tags":['SC', 'SC', 'D', 'D', 'AX', 'D', 'N', 'AX']}),
]

@plac.annotations(
    model = ("Nombre del modelo. De forma predeterminada se selecciona el modelo: es_core_news_md.", "option", "m", str),
    output_dir = ("C:\\Users\\Alex Isasi\\Documents\\GitHub\\EvaluacionCognitiva\\modelos", "option", "o", Path),
    n_iter=("Número de iteraciones de entrenamiento.", "option", "n", int))

def main(model = "es_core_news_md", output_dir = 'C:\\Users\\Alex Isasi\\Documents\\GitHub\\EvaluacionCognitiva\\model_x', n_iter = 40):
    #output_dir = 'C:\\Users\\Alex Isasi\\Documents\\GitHub\\EvaluacionCognitiva\\modelos'   #ruta destino
    #n_iter = 100     #Iteraciones en el entrenamiento
    #model = "es_core_news_md"       #modelo o lenguaje de base
    if model is not None:
        nlp = spacy.load(model)
        print("Cargando modelo: '%s'" % model)
    else:
        nlp = spacy.blank('es')
        print("Se ha creado el modelo 'es' desde cero.")

    tagger = nlp.create_pipe("tagger")

    for tag, values in TAG_MAP.items():
        tagger.add_label(tag, values)
    #nlp.add_pipe(tagger)

    other_pipes = [pipe for pipe in nlp.pipe_names if pipe != 'tagger']
    with nlp.disable_pipes(*other_pipes):   #Sólo se entrenará TAGGER
        nlp.vocab.vectors.name = 'spacy_pretrained_vectors'
        optimizer = nlp.begin_training()
        for i in range(n_iter):
            random.shuffle(TRAIN_DATA)
            losses = {}
            batches = minibatch(TRAIN_DATA, size=compounding(4.0, 32.0, 1.001))
            #for text, annotations in tqdm(TRAIN_DATA):
             #   nlp.update([text], [annotations], sgd = optimizer, losses=losses)
            for batch in batches:
                texts, annotations = zip(*batch) 
                nlp.update(texts, annotations, sgd=optimizer, losses=losses)
            print("Losses: ",losses)

    # test the trained model
    test_text = "pelota no puede cantar"
   # doc = nlp(test_text)
   # print("Tags", [(t.text, t.tag_, t.pos_) for t in doc])

    # save model to output directory
    if output_dir is not None:
        output_dir = Path(output_dir)
        if not output_dir.exists():
            output_dir.mkdir()
        nlp.to_disk(output_dir)
        print("Guardando modelo a:", output_dir)

        # test the save model
        print("Cargando modelo:", output_dir)
        print("Prueba final.")
        nlp2 = spacy.load(output_dir)
        doc = nlp2(test_text)
        print("Tags", [(t.text, t.tag_, t.pos_) for t in doc])

if __name__ == "__main__":
    plac.call(main)